# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "lift"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_lift_faceTopPlate_Fa0_Ctr0():
	P000 = App.Vector(-60.6218, 0.0000, 0)
	P001 = App.Vector(60.6218, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(60.6218, 20.8453, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(60.3538, 21.8453, 0)
	P004 = App.Vector(59.6218, 22.5774, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(45.0000, 31.0192, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(44.0785, 32.1966, 0)
	P007 = App.Vector(44.2308, 33.6839, 0)
	S004 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(0.0000, 107.0000, 0)
	P009 = App.Vector(-44.2308, 33.6839, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-44.0785, 32.1966, 0)
	P011 = App.Vector(-45.0000, 31.0192, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-59.6218, 22.5774, 0)
	S007 = Part.LineSegment(P011, P012)
	P013 = App.Vector(-60.3538, 21.8453, 0)
	P014 = App.Vector(-60.6218, 20.8453, 0)
	S008 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(-60.6218, 0.0000, 0)
	S009 = Part.LineSegment(P014, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_lift_faceTopPlate_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(30.0000, App.Vector(0.0000, 57.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_lift_faceTopPlate_Fa0():
	FC000 = ctr_face_lift_faceTopPlate_Fa0_Ctr0()
	FC001 = ctr_face_lift_faceTopPlate_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def lift_faceTopPlate():
	FA000 = face_lift_faceTopPlate_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_lift_faceTopEnd_Fa0_Ctr0():
	P000 = App.Vector(-60.6218, 0.0000, 0)
	P001 = App.Vector(60.6218, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(60.6218, 20.8453, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(60.3538, 21.8453, 0)
	P004 = App.Vector(59.6218, 22.5774, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(45.0000, 31.0192, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(44.0785, 32.1966, 0)
	P007 = App.Vector(44.2308, 33.6839, 0)
	S004 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(0.0000, 107.0000, 0)
	P009 = App.Vector(-44.2308, 33.6839, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-44.0785, 32.1966, 0)
	P011 = App.Vector(-45.0000, 31.0192, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-59.6218, 22.5774, 0)
	S007 = Part.LineSegment(P011, P012)
	P013 = App.Vector(-60.3538, 21.8453, 0)
	P014 = App.Vector(-60.6218, 20.8453, 0)
	S008 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(-60.6218, 0.0000, 0)
	S009 = Part.LineSegment(P014, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_lift_faceTopEnd_Fa0_Ctr1():
	P000 = App.Vector(-56.6218, 6.0000, 0)
	P001 = App.Vector(-4.5000, 6.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-3.0858, 6.5858, 0)
	P003 = App.Vector(-2.5000, 8.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-2.5000, 20.2747, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-3.0023, 21.6001, 0)
	P006 = App.Vector(-4.2568, 22.2598, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-0.0000, 92.0000, 0)
	P008 = App.Vector(4.2568, 22.2598, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(3.0023, 21.6001, 0)
	P010 = App.Vector(2.5000, 20.2747, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(2.5000, 8.0000, 0)
	S006 = Part.LineSegment(P010, P011)
	P012 = App.Vector(3.0858, 6.5858, 0)
	P013 = App.Vector(4.5000, 6.0000, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(56.6218, 6.0000, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(58.0360, 6.5858, 0)
	P016 = App.Vector(58.6218, 8.0000, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(58.6218, 19.6906, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(58.3538, 20.6906, 0)
	P019 = App.Vector(57.6218, 21.4226, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(42.3013, 30.2679, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(41.3694, 31.4824, 0)
	P022 = App.Vector(41.5692, 33.0000, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(0.0000, 105.0000, 0)
	P024 = App.Vector(-41.5692, 33.0000, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-41.3694, 31.4824, 0)
	P026 = App.Vector(-42.3013, 30.2679, 0)
	S015 = Part.Arc(P024, P025, P026)
	P027 = App.Vector(-57.6218, 21.4226, 0)
	S016 = Part.LineSegment(P026, P027)
	P028 = App.Vector(-58.3538, 20.6906, 0)
	P029 = App.Vector(-58.6218, 19.6906, 0)
	S017 = Part.Arc(P027, P028, P029)
	P030 = App.Vector(-58.6218, 8.0000, 0)
	S018 = Part.LineSegment(P029, P030)
	P031 = App.Vector(-58.0360, 6.5858, 0)
	P032 = App.Vector(-56.6218, 6.0000, 0)
	S019 = Part.Arc(P030, P031, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_lift_faceTopEnd_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(30.0000, App.Vector(0.0000, 57.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_lift_faceTopEnd_Fa0():
	FC000 = ctr_face_lift_faceTopEnd_Fa0_Ctr0()
	FC001 = ctr_face_lift_faceTopEnd_Fa0_Ctr1()
	FC002 = ctr_face_lift_faceTopEnd_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def lift_faceTopEnd():
	FA000 = face_lift_faceTopEnd_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_lift_faceTopBack_Fa0_Ctr0():
	P000 = App.Vector(-60.6218, 0.0000, 0)
	P001 = App.Vector(60.6218, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(60.6218, 4.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(60.0360, 5.4142, 0)
	P004 = App.Vector(58.6218, 6.0000, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(-58.6218, 6.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-60.0360, 5.4142, 0)
	P007 = App.Vector(-60.6218, 4.0000, 0)
	S004 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(-60.6218, 0.0000, 0)
	S005 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_lift_faceTopBack_Fa0():
	FC000 = ctr_face_lift_faceTopBack_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def lift_faceTopBack():
	FA000 = face_lift_faceTopBack_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_lift_faceTopDisc_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(50.0000, App.Vector(0.0000, 57.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_lift_faceTopDisc_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(30.0000, App.Vector(0.0000, 57.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_lift_faceTopDisc_Fa0():
	FC000 = ctr_face_lift_faceTopDisc_Fa0_Ctr0()
	FC001 = ctr_face_lift_faceTopDisc_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def lift_faceTopDisc():
	FA000 = face_lift_faceTopDisc_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_lift_faceSideL_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(0.0000, 146.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-4.3734, 153.5415, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-40.5386, 161.3379, 0)
	P004 = App.Vector(-44.8652, 124.5956, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(-5.7058, 79.5617, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-3.2519, 73.0000, 0)
	P007 = App.Vector(-5.7058, 66.4383, 0)
	S004 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(-44.8652, 21.4044, 0)
	S005 = Part.LineSegment(P007, P008)
	P009 = App.Vector(-40.5386, -15.3379, 0)
	P010 = App.Vector(-4.3734, -7.5415, 0)
	S006 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(0.0000, 0.0000, 0)
	S007 = Part.LineSegment(P010, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_lift_faceSideL_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(-26.0000, 141.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_lift_faceSideL_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(-26.0000, 5.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_lift_faceSideL_Fa0():
	FC000 = ctr_face_lift_faceSideL_Fa0_Ctr0()
	FC001 = ctr_face_lift_faceSideL_Fa0_Ctr1()
	FC002 = ctr_face_lift_faceSideL_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def lift_faceSideL():
	FA000 = face_lift_faceSideL_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_lift_faceSideM_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(0.0000, 75.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-26.0000, 75.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-49.7635, 57.7651, 0)
	P004 = App.Vector(-40.7621, 29.8237, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_lift_faceSideM_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(-26.0000, 50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_lift_faceSideM_Fa0():
	FC000 = ctr_face_lift_faceSideM_Fa0_Ctr0()
	FC001 = ctr_face_lift_faceSideM_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def lift_faceSideM():
	FA000 = face_lift_faceSideM_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_lift_faceBack_Fa0_Ctr0():
	P000 = App.Vector(-60.6218, 0.0000, 0)
	P001 = App.Vector(60.6218, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(60.6218, 146.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-60.6218, 146.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-60.6218, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_lift_faceBack_Fa0():
	FC000 = ctr_face_lift_faceBack_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_lift_faceBack_Fa1_Ctr0():
	P000 = App.Vector(-60.6218, 0.0000, 0)
	P001 = App.Vector(-57.6218, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-57.6218, 146.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-60.6218, 146.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-60.6218, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_lift_faceBack_Fa1():
	FC000 = ctr_face_lift_faceBack_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_lift_faceBack_Fa2_Ctr0():
	P000 = App.Vector(-47.6218, 0.0000, 0)
	P001 = App.Vector(-44.6218, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-44.6218, 146.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-47.6218, 146.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-47.6218, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_lift_faceBack_Fa2():
	FC000 = ctr_face_lift_faceBack_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_lift_faceBack_Fa3_Ctr0():
	P000 = App.Vector(-8.0000, 0.0000, 0)
	P001 = App.Vector(-5.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-5.0000, 75.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-8.0000, 75.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-8.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_lift_faceBack_Fa3():
	FC000 = ctr_face_lift_faceBack_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_lift_faceBack_Fa4_Ctr0():
	P000 = App.Vector(5.0000, 0.0000, 0)
	P001 = App.Vector(8.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(8.0000, 75.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(5.0000, 75.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(5.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_lift_faceBack_Fa4():
	FC000 = ctr_face_lift_faceBack_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_lift_faceBack_Fa5_Ctr0():
	P000 = App.Vector(44.6218, 0.0000, 0)
	P001 = App.Vector(47.6218, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(47.6218, 146.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(44.6218, 146.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(44.6218, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_lift_faceBack_Fa5():
	FC000 = ctr_face_lift_faceBack_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_lift_faceBack_Fa6_Ctr0():
	P000 = App.Vector(57.6218, 0.0000, 0)
	P001 = App.Vector(60.6218, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(60.6218, 146.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(57.6218, 146.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(57.6218, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_lift_faceBack_Fa6():
	FC000 = ctr_face_lift_faceBack_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def lift_faceBack():
	FA000 = face_lift_faceBack_Fa0()
	FA001 = face_lift_faceBack_Fa1()
	FA002 = face_lift_faceBack_Fa2()
	FA003 = face_lift_faceBack_Fa3()
	FA004 = face_lift_faceBack_Fa4()
	FA005 = face_lift_faceBack_Fa5()
	FA006 = face_lift_faceBack_Fa6()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006])
	rOneFig.check()
	return rOneFig

def fex_subpax_lift_end1():
	FIG = lift_faceTopEnd()
	VEX = FIG.extrude(App.Vector(0, 0, 25))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_lift_end1 = fex_subpax_lift_end1()

def fex_subpax_lift_plate1():
	FIG = lift_faceTopPlate()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 25.0000))
	return VFP
subpax_lift_plate1 = fex_subpax_lift_plate1()

def fex_subpax_lift_wall():
	FIG = lift_faceTopBack()
	VEX = FIG.extrude(App.Vector(0, 0, 100))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 28.0000))
	return VFP
subpax_lift_wall = fex_subpax_lift_wall()

def fex_subpax_lift_plate2():
	FIG = lift_faceTopPlate()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 128.0000))
	return VFP
subpax_lift_plate2 = fex_subpax_lift_plate2()

def fex_subpax_lift_end2():
	FIG = lift_faceTopEnd()
	VEX = FIG.extrude(App.Vector(0, 0, 15))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 131.0000))
	return VFP
subpax_lift_end2 = fex_subpax_lift_end2()

def fex_subpax_lift_disc1():
	FIG = lift_faceTopDisc()
	VEX = FIG.extrude(App.Vector(0, 0, 0.5))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 28.0000))
	return VFP
subpax_lift_disc1 = fex_subpax_lift_disc1()

def fex_subpax_lift_disc2():
	FIG = lift_faceTopDisc()
	VEX = FIG.extrude(App.Vector(0, 0, 0.5))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 130.5000))
	return VFP
subpax_lift_disc2 = fex_subpax_lift_disc2()

def fex_subpax_lift_L1():
	FIG = lift_faceSideL()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(-60.6218, 0.0000, 0.0000))
	return VFP
subpax_lift_L1 = fex_subpax_lift_L1()

def fex_subpax_lift_L2():
	FIG = lift_faceSideL()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(-47.6218, 0.0000, 0.0000))
	return VFP
subpax_lift_L2 = fex_subpax_lift_L2()

def fex_subpax_lift_L3():
	FIG = lift_faceSideL()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(44.6218, 0.0000, 0.0000))
	return VFP
subpax_lift_L3 = fex_subpax_lift_L3()

def fex_subpax_lift_L4():
	FIG = lift_faceSideL()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(57.6218, 0.0000, 0.0000))
	return VFP
subpax_lift_L4 = fex_subpax_lift_L4()

def fex_subpax_lift_M1():
	FIG = lift_faceSideM()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(-8.0000, 0.0000, 0.0000))
	return VFP
subpax_lift_M1 = fex_subpax_lift_M1()

def fex_subpax_lift_M2():
	FIG = lift_faceSideM()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(5.0000, 0.0000, 0.0000))
	return VFP
subpax_lift_M2 = fex_subpax_lift_M2()

def fvol_pax_lift():
	V000 = subpax_lift_end1
	V001 = V000.fuse(subpax_lift_plate1)
	V002 = V001.fuse(subpax_lift_wall)
	V003 = V002.fuse(subpax_lift_plate2)
	V004 = V003.fuse(subpax_lift_end2)
	V005 = V004.fuse(subpax_lift_disc1)
	V006 = V005.fuse(subpax_lift_disc2)
	V007 = V006.fuse(subpax_lift_L1)
	V008 = V007.fuse(subpax_lift_L2)
	V009 = V008.fuse(subpax_lift_L3)
	V010 = V009.fuse(subpax_lift_L4)
	V011 = V010.fuse(subpax_lift_M1)
	V012 = V011.fuse(subpax_lift_M2)
	VFC = V012.removeSplitter()
	return VFC
pax_lift = fvol_pax_lift()


pax_lift.check()
#pax_lift.exportBrep(f"{outFileName}.brep")
#pax_lift.exportIges(f"{outFileName}.igs")
#pax_lift.exportStep(f"{outFileName}.stp")
pax_lift.exportStl(f"{outFileName}.stl")

