# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "long2d"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_long2d_faceTop_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(3.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(3.0000, 20.1683, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(2.9723, 20.5001, 0)
	P004 = App.Vector(2.8899, 20.8228, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(-14.8532, 72.0517, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(40.0000, 149.1000, 0)
	P007 = App.Vector(94.8532, 72.0517, 0)
	S004 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(77.1101, 20.8228, 0)
	S005 = Part.LineSegment(P007, P008)
	P009 = App.Vector(77.0277, 20.5001, 0)
	P010 = App.Vector(77.0000, 20.1683, 0)
	S006 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(77.0000, 0.0000, 0)
	S007 = Part.LineSegment(P010, P011)
	P012 = App.Vector(80.0000, 0.0000, 0)
	S008 = Part.LineSegment(P011, P012)
	P013 = App.Vector(80.0000, 19.6635, 0)
	S009 = Part.LineSegment(P012, P013)
	P014 = App.Vector(80.0277, 19.9953, 0)
	P015 = App.Vector(80.1101, 20.3180, 0)
	S010 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(97.6879, 71.0699, 0)
	S011 = Part.LineSegment(P015, P016)
	P017 = App.Vector(40.0000, 152.1000, 0)
	P018 = App.Vector(-17.6879, 71.0699, 0)
	S012 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-0.1101, 20.3180, 0)
	S013 = Part.LineSegment(P018, P019)
	P020 = App.Vector(-0.0277, 19.9953, 0)
	P021 = App.Vector(0.0000, 19.6635, 0)
	S014 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(0.0000, 0.0000, 0)
	S015 = Part.LineSegment(P021, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceTop_Fa0():
	FC000 = ctr_face_long2d_faceTop_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_long2d_faceTop_Fa1_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(13.3500, App.Vector(40.0000, 91.0500, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_long2d_faceTop_Fa1_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.3500, App.Vector(40.0000, 91.0500, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_long2d_faceTop_Fa1():
	FC000 = ctr_face_long2d_faceTop_Fa1_Ctr0()
	FC001 = ctr_face_long2d_faceTop_Fa1_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_long2d_faceTop_Fa2_Ctr0():
	P000 = App.Vector(67.3393, 168.5355, 0)
	P001 = App.Vector(136.2910, 201.5617, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(145.0975, 204.7633, 0)
	P003 = App.Vector(154.3599, 206.1816, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(155.1013, 205.9088, 0)
	P005 = App.Vector(155.4134, 205.1830, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(155.4134, 172.6806, 0)
	S003 = Part.LineSegment(P005, P006)
	P007 = App.Vector(155.1797, 172.0380, 0)
	P008 = App.Vector(154.5876, 171.6958, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(145.3520, 165.2250, 0)
	P010 = App.Vector(144.3659, 153.9913, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(144.3656, 153.3075, 0)
	P012 = App.Vector(143.9260, 152.7838, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(93.3333, 123.5740, 0)
	S007 = Part.LineSegment(P012, P013)
	P014 = App.Vector(93.1469, 123.3312, 0)
	P015 = App.Vector(93.1869, 123.0276, 0)
	S008 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(94.2869, 121.1224, 0)
	S009 = Part.LineSegment(P015, P016)
	P017 = App.Vector(94.5298, 120.9360, 0)
	P018 = App.Vector(94.8333, 120.9760, 0)
	S010 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(145.4260, 150.1857, 0)
	S011 = Part.LineSegment(P018, P019)
	P020 = App.Vector(146.0994, 150.3045, 0)
	P021 = App.Vector(146.6917, 149.9629, 0)
	S012 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(156.9134, 145.2000, 0)
	P023 = App.Vector(167.1352, 149.9629, 0)
	S013 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(167.7275, 150.3045, 0)
	P025 = App.Vector(168.4008, 150.1857, 0)
	S014 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(196.5488, 133.9344, 0)
	S015 = Part.LineSegment(P025, P026)
	P027 = App.Vector(197.0213, 133.3013, 0)
	P028 = App.Vector(196.8868, 132.5228, 0)
	S016 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(191.0274, 125.2104, 0)
	P030 = App.Vector(183.8514, 119.1846, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(120.7740, 75.9838, 0)
	S018 = Part.LineSegment(P030, P031)
	P032 = App.Vector(120.6100, 75.7424, 0)
	P033 = App.Vector(120.6536, 75.4538, 0)
	S019 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(121.7569, 73.5430, 0)
	S020 = Part.LineSegment(P033, P034)
	P035 = App.Vector(122.0147, 73.3529, 0)
	P036 = App.Vector(122.3293, 73.4129, 0)
	S021 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(185.5456, 116.7088, 0)
	S022 = Part.LineSegment(P036, P037)
	P038 = App.Vector(200.8209, 183.9000, 0)
	P039 = App.Vector(134.9940, 204.2668, 0)
	S023 = Part.Arc(P037, P038, P039)
	P040 = App.Vector(65.8905, 171.1678, 0)
	S024 = Part.LineSegment(P039, P040)
	P041 = App.Vector(65.6812, 170.9254, 0)
	P042 = App.Vector(65.7169, 170.6070, 0)
	S025 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(66.8201, 168.6962, 0)
	S026 = Part.LineSegment(P042, P043)
	P044 = App.Vector(67.0482, 168.5141, 0)
	P045 = App.Vector(67.3393, 168.5355, 0)
	S027 = Part.Arc(P043, P044, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_long2d_faceTop_Fa2_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.3500, App.Vector(156.9134, 158.5500, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_long2d_faceTop_Fa2_Ctr2():
	P000 = App.Vector(159.2392, 171.6958, 0)
	P001 = App.Vector(168.4749, 165.2250, 0)
	P002 = App.Vector(169.4610, 153.9913, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(169.4613, 153.3075, 0)
	P004 = App.Vector(169.9008, 152.7838, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(198.0488, 136.5325, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(198.8334, 136.4399, 0)
	P007 = App.Vector(199.4404, 136.9456, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(198.2228, 182.4000, 0)
	P009 = App.Vector(159.4670, 206.1816, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(158.7255, 205.9088, 0)
	P011 = App.Vector(158.4134, 205.1830, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(158.4134, 172.6806, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(158.6472, 172.0380, 0)
	P014 = App.Vector(159.2392, 171.6958, 0)
	S007 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceTop_Fa2():
	FC000 = ctr_face_long2d_faceTop_Fa2_Ctr0()
	FC001 = ctr_face_long2d_faceTop_Fa2_Ctr1()
	FC002 = ctr_face_long2d_faceTop_Fa2_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def ctr_face_long2d_faceTop_Fa3_Ctr0():
	P000 = App.Vector(144.2853, 225.0783, 0)
	P001 = App.Vector(182.9264, 282.2220, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(187.2593, 287.5177, 0)
	P003 = App.Vector(192.4856, 291.9342, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(193.2667, 292.0925, 0)
	P005 = App.Vector(193.9155, 291.6295, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(205.3150, 272.6575, 0)
	S003 = Part.LineSegment(P005, P006)
	P007 = App.Vector(205.4456, 271.9863, 0)
	P008 = App.Vector(205.1144, 271.3881, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(200.5306, 261.0848, 0)
	P010 = App.Vector(205.4712, 250.9478, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(205.8231, 250.3615, 0)
	P012 = App.Vector(205.7160, 249.6862, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(180.8601, 204.8449, 0)
	S007 = Part.LineSegment(P012, P013)
	P014 = App.Vector(180.8254, 204.5407, 0)
	P015 = App.Vector(181.0160, 204.3011, 0)
	S008 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(182.9402, 203.2345, 0)
	S009 = Part.LineSegment(P015, P016)
	P017 = App.Vector(183.2443, 203.1999, 0)
	P018 = App.Vector(183.4839, 203.3905, 0)
	S010 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(208.3399, 248.2317, 0)
	S011 = Part.LineSegment(P018, P019)
	P020 = App.Vector(208.8558, 248.6804, 0)
	P021 = App.Vector(209.5395, 248.6926, 0)
	S012 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(220.7543, 249.8746, 0)
	P023 = App.Vector(227.0630, 259.2218, 0)
	S013 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(227.3947, 259.8197, 0)
	P025 = App.Vector(228.0331, 260.0647, 0)
	S014 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(250.1631, 260.4509, 0)
	S015 = Part.LineSegment(P025, P026)
	P027 = App.Vector(250.8996, 260.1461, 0)
	P028 = App.Vector(251.1793, 259.3997, 0)
	S016 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(250.2034, 252.6272, 0)
	P030 = App.Vector(248.0085, 246.1464, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(220.0245, 183.0953, 0)
	S018 = Part.LineSegment(P030, P031)
	P032 = App.Vector(220.0108, 182.8059, 0)
	P033 = App.Vector(220.1962, 182.5832, 0)
	S019 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(222.1277, 181.5125, 0)
	S020 = Part.LineSegment(P033, P034)
	P035 = App.Vector(222.4488, 181.4831, 0)
	P036 = App.Vector(222.6873, 181.7001, 0)
	S021 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(250.7498, 244.9278, 0)
	S022 = Part.LineSegment(P036, P037)
	P038 = App.Vector(233.4406, 296.6087, 0)
	P039 = App.Vector(180.4403, 283.9010, 0)
	S023 = Part.Arc(P037, P038, P039)
	P040 = App.Vector(141.6910, 226.5971, 0)
	S024 = Part.LineSegment(P039, P040)
	P041 = App.Vector(141.6333, 226.2799, 0)
	P042 = App.Vector(141.8284, 226.0232, 0)
	S025 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(143.7600, 224.9525, 0)
	S026 = Part.LineSegment(P042, P043)
	P044 = App.Vector(144.0471, 224.9133, 0)
	P045 = App.Vector(144.2853, 225.0783, 0)
	S027 = Part.Arc(P043, P044, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_long2d_faceTop_Fa3_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.3500, App.Vector(213.8786, 261.3178, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_long2d_faceTop_Fa3_Ctr2():
	P000 = App.Vector(209.1015, 273.7839, 0)
	P001 = App.Vector(220.3508, 272.9940, 0)
	P002 = App.Vector(226.9818, 263.8727, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(227.3342, 263.2867, 0)
	P004 = App.Vector(227.9808, 263.0642, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(250.1108, 263.4505, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(250.8361, 263.7808, 0)
	P007 = App.Vector(251.0896, 264.5365, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(231.9862, 293.9849, 0)
	P009 = App.Vector(196.8893, 294.5802, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(196.3828, 293.9648, 0)
	P011 = App.Vector(196.4870, 293.1746, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(207.8865, 274.2026, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(208.4179, 273.7722, 0)
	P014 = App.Vector(209.1015, 273.7839, 0)
	S007 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceTop_Fa3():
	FC000 = ctr_face_long2d_faceTop_Fa3_Ctr0()
	FC001 = ctr_face_long2d_faceTop_Fa3_Ctr1()
	FC002 = ctr_face_long2d_faceTop_Fa3_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def ctr_face_long2d_faceTop_Fa4_Ctr0():
	P000 = App.Vector(163.0046, 277.3124, 0)
	P001 = App.Vector(134.1398, 331.5080, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(132.4004, 335.5185, 0)
	P003 = App.Vector(131.3309, 339.7570, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(131.5318, 340.5414, 0)
	P005 = App.Vector(132.2474, 340.9200, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(143.9678, 341.7395, 0)
	S003 = Part.LineSegment(P005, P006)
	P007 = App.Vector(144.6251, 341.5512, 0)
	P008 = App.Vector(145.0077, 340.9844, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(152.1070, 332.2227, 0)
	P010 = App.Vector(163.3822, 332.0226, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(164.0643, 332.0700, 0)
	P012 = App.Vector(164.6174, 331.6680, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(189.2887, 295.0913, 0)
	S007 = Part.LineSegment(P012, P013)
	P014 = App.Vector(189.5440, 294.9224, 0)
	P015 = App.Vector(189.8440, 294.9834, 0)
	S008 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(191.6679, 296.2136, 0)
	S009 = Part.LineSegment(P015, P016)
	P017 = App.Vector(191.8368, 296.4689, 0)
	P018 = App.Vector(191.7758, 296.7689, 0)
	S010 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(167.1045, 333.3456, 0)
	S011 = Part.LineSegment(P018, P019)
	P020 = App.Vector(166.9390, 334.0090, 0)
	P021 = App.Vector(167.2385, 334.6237, 0)
	S012 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(171.2767, 345.1528, 0)
	P023 = App.Vector(165.8124, 355.0174, 0)
	S013 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(165.4303, 355.5845, 0)
	P025 = App.Vector(165.5019, 356.2645, 0)
	S014 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(170.6523, 366.8244, 0)
	S015 = Part.LineSegment(P025, P026)
	P027 = App.Vector(171.2714, 367.3461, 0)
	P028 = App.Vector(172.0739, 367.2385, 0)
	S016 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(175.6032, 364.6591, 0)
	P030 = App.Vector(178.6700, 361.5440, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(218.1064, 314.4790, 0)
	S018 = Part.LineSegment(P030, P031)
	P032 = App.Vector(218.3572, 314.3398, 0)
	P033 = App.Vector(218.6366, 314.4043, 0)
	S019 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(220.4702, 315.6410, 0)
	S020 = Part.LineSegment(P033, P034)
	P035 = App.Vector(220.6426, 315.9169, 0)
	P036 = App.Vector(220.5531, 316.2296, 0)
	S021 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(180.9712, 363.4687, 0)
	S022 = Part.LineSegment(P036, P037)
	P038 = App.Vector(141.1835, 369.0927, 0)
	P039 = App.Vector(131.4932, 330.0954, 0)
	S023 = Part.Arc(P037, P038, P039)
	P040 = App.Vector(160.4649, 275.6996, 0)
	S024 = Part.LineSegment(P039, P040)
	P041 = App.Vector(160.7214, 275.4995, 0)
	P042 = App.Vector(161.0417, 275.5560, 0)
	S025 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(162.8752, 276.7927, 0)
	S026 = Part.LineSegment(P042, P043)
	P044 = App.Vector(163.0397, 277.0277, 0)
	P045 = App.Vector(163.0046, 277.3124, 0)
	S027 = Part.Arc(P043, P044, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_long2d_faceTop_Fa4_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.3500, App.Vector(157.9593, 344.2216, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_long2d_faceTop_Fa4_Ctr2():
	P000 = App.Vector(144.6832, 345.6247, 0)
	P001 = App.Vector(150.4940, 355.2892, 0)
	P002 = App.Vector(161.6316, 357.0565, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(162.3137, 357.1045, 0)
	P004 = App.Vector(162.8055, 357.5796, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(167.9559, 368.1395, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(167.9859, 368.9486, 0)
	P007 = App.Vector(167.4070, 369.5146, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(142.8611, 366.6056, 0)
	P009 = App.Vector(130.9687, 344.9367, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(131.2768, 344.1880, 0)
	P011 = App.Vector(132.0381, 343.9127, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(143.7585, 344.7322, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(144.3832, 345.0102, 0)
	P014 = App.Vector(144.6832, 345.6247, 0)
	S007 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceTop_Fa4():
	FC000 = ctr_face_long2d_faceTop_Fa4_Ctr0()
	FC001 = ctr_face_long2d_faceTop_Fa4_Ctr1()
	FC002 = ctr_face_long2d_faceTop_Fa4_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def long2d_faceTop():
	FA000 = face_long2d_faceTop_Fa0()
	FA001 = face_long2d_faceTop_Fa1()
	FA002 = face_long2d_faceTop_Fa2()
	FA003 = face_long2d_faceTop_Fa3()
	FA004 = face_long2d_faceTop_Fa4()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004])
	rOneFig.check()
	return rOneFig

def ctr_face_long2d_faceSide_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 10.0000, 0)
	P001 = App.Vector(77.7000, 10.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(77.7000, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(80.7000, 0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(80.7000, 20.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(10.0000, 20.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(10.0000, 131.5000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(80.7000, 131.5000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(80.7000, 151.5000, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(77.7000, 151.5000, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(77.7000, 141.5000, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(0.0000, 141.5000, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(0.0000, 10.0000, 0)
	S011 = Part.LineSegment(P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceSide_Fa0():
	FC000 = ctr_face_long2d_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_long2d_faceSide_Fa1_Ctr0():
	P000 = App.Vector(101.4000, 0.0000, 0)
	P001 = App.Vector(104.4000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(104.4000, 10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(149.1000, 10.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(149.1000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(152.1000, 0.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(152.1000, 20.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(101.4000, 20.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(101.4000, 0.0000, 0)
	S007 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceSide_Fa1():
	FC000 = ctr_face_long2d_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_long2d_faceSide_Fa2_Ctr0():
	P000 = App.Vector(101.4000, 131.5000, 0)
	P001 = App.Vector(152.1000, 131.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(152.1000, 151.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(149.1000, 151.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(149.1000, 141.5000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(104.4000, 141.5000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(104.4000, 151.5000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(101.4000, 151.5000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(101.4000, 131.5000, 0)
	S007 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceSide_Fa2():
	FC000 = ctr_face_long2d_faceSide_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_long2d_faceSide_Fa3_Ctr0():
	P000 = App.Vector(81.0500, 0.0000, 0)
	P001 = App.Vector(86.0500, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(86.0500, 151.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(81.0500, 151.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(81.0500, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceSide_Fa3():
	FC000 = ctr_face_long2d_faceSide_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_long2d_faceSide_Fa4_Ctr0():
	P000 = App.Vector(96.0500, 0.0000, 0)
	P001 = App.Vector(101.0500, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(101.0500, 151.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(96.0500, 151.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(96.0500, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceSide_Fa4():
	FC000 = ctr_face_long2d_faceSide_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_long2d_faceSide_Fa5_Ctr0():
	P000 = App.Vector(30.0000, 20.2500, 0)
	P001 = App.Vector(276.7500, 20.2500, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(276.7500, 30.2500, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(30.0000, 30.2500, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(30.0000, 20.2500, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceSide_Fa5():
	FC000 = ctr_face_long2d_faceSide_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_long2d_faceSide_Fa6_Ctr0():
	P000 = App.Vector(30.0000, 121.2500, 0)
	P001 = App.Vector(276.7500, 121.2500, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(276.7500, 131.2500, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(30.0000, 131.2500, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(30.0000, 121.2500, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceSide_Fa6():
	FC000 = ctr_face_long2d_faceSide_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_long2d_faceSide_Fa7_Ctr0():
	P000 = App.Vector(216.0500, 10.2500, 0)
	P001 = App.Vector(221.0500, 10.2500, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(221.0500, 141.2500, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(216.0500, 141.2500, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(216.0500, 10.2500, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceSide_Fa7():
	FC000 = ctr_face_long2d_faceSide_Fa7_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_long2d_faceSide_Fa8_Ctr0():
	P000 = App.Vector(231.0500, 10.2500, 0)
	P001 = App.Vector(236.0500, 10.2500, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(236.0500, 141.2500, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(231.0500, 141.2500, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(231.0500, 10.2500, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceSide_Fa8():
	FC000 = ctr_face_long2d_faceSide_Fa8_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_long2d_faceSide_Fa9_Ctr0():
	P000 = App.Vector(175.3500, 30.5000, 0)
	P001 = App.Vector(383.9000, 30.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(383.9000, 40.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(175.3500, 40.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(175.3500, 30.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceSide_Fa9():
	FC000 = ctr_face_long2d_faceSide_Fa9_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_long2d_faceSide_Fa10_Ctr0():
	P000 = App.Vector(175.3500, 111.0000, 0)
	P001 = App.Vector(383.9000, 111.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(383.9000, 121.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(175.3500, 121.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(175.3500, 111.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceSide_Fa10():
	FC000 = ctr_face_long2d_faceSide_Fa10_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_long2d_faceSide_Fa11_Ctr0():
	P000 = App.Vector(333.5500, 20.5000, 0)
	P001 = App.Vector(338.5500, 20.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(338.5500, 131.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(333.5500, 131.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(333.5500, 20.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceSide_Fa11():
	FC000 = ctr_face_long2d_faceSide_Fa11_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_long2d_faceSide_Fa12_Ctr0():
	P000 = App.Vector(348.5500, 20.5000, 0)
	P001 = App.Vector(353.5500, 20.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(353.5500, 131.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(348.5500, 131.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(348.5500, 20.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceSide_Fa12():
	FC000 = ctr_face_long2d_faceSide_Fa12_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_long2d_faceSide_Fa13_Ctr0():
	P000 = App.Vector(303.2000, 40.7500, 0)
	P001 = App.Vector(473.5500, 40.7500, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(473.5500, 50.7500, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(303.2000, 50.7500, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(303.2000, 40.7500, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceSide_Fa13():
	FC000 = ctr_face_long2d_faceSide_Fa13_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_long2d_faceSide_Fa14_Ctr0():
	P000 = App.Vector(303.2000, 100.7500, 0)
	P001 = App.Vector(473.5500, 100.7500, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(473.5500, 110.7500, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(303.2000, 110.7500, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(303.2000, 100.7500, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_long2d_faceSide_Fa14():
	FC000 = ctr_face_long2d_faceSide_Fa14_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def long2d_faceSide():
	FA000 = face_long2d_faceSide_Fa0()
	FA001 = face_long2d_faceSide_Fa1()
	FA002 = face_long2d_faceSide_Fa2()
	FA003 = face_long2d_faceSide_Fa3()
	FA004 = face_long2d_faceSide_Fa4()
	FA005 = face_long2d_faceSide_Fa5()
	FA006 = face_long2d_faceSide_Fa6()
	FA007 = face_long2d_faceSide_Fa7()
	FA008 = face_long2d_faceSide_Fa8()
	FA009 = face_long2d_faceSide_Fa9()
	FA010 = face_long2d_faceSide_Fa10()
	FA011 = face_long2d_faceSide_Fa11()
	FA012 = face_long2d_faceSide_Fa12()
	FA013 = face_long2d_faceSide_Fa13()
	FA014 = face_long2d_faceSide_Fa14()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006, FA007, FA008, FA009, FA010, FA011, FA012, FA013, FA014])
	rOneFig.check()
	return rOneFig

def ctr_face_long2d_faceBack_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 20.0000, 0)
	P001 = App.Vector(80.0000, 20.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(80.0000, 131.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 131.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 20.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_long2d_faceBack_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.5000, App.Vector(30.0000, 60.7500, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_long2d_faceBack_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.5000, App.Vector(50.0000, 60.7500, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_long2d_faceBack_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.5000, App.Vector(30.0000, 90.7500, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_long2d_faceBack_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.5000, App.Vector(50.0000, 90.7500, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_long2d_faceBack_Fa0():
	FC000 = ctr_face_long2d_faceBack_Fa0_Ctr0()
	FC001 = ctr_face_long2d_faceBack_Fa0_Ctr1()
	FC002 = ctr_face_long2d_faceBack_Fa0_Ctr2()
	FC003 = ctr_face_long2d_faceBack_Fa0_Ctr3()
	FC004 = ctr_face_long2d_faceBack_Fa0_Ctr4()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004])
	rOneFace.check()
	return rOneFace

def long2d_faceBack():
	FA000 = face_long2d_faceBack_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_long2d_faceAxis_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_long2d_faceAxis_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_long2d_faceAxis_Fa0():
	FC000 = ctr_face_long2d_faceAxis_Fa0_Ctr0()
	FC001 = ctr_face_long2d_faceAxis_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def long2d_faceAxis():
	FA000 = face_long2d_faceAxis_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scarabase_facePlate_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(80.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(80.0000, 19.6635, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(80.0277, 19.9953, 0)
	P004 = App.Vector(80.1101, 20.3180, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(97.6879, 71.0699, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(40.0000, 152.1000, 0)
	P007 = App.Vector(-17.6879, 71.0699, 0)
	S004 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(-0.1101, 20.3180, 0)
	S005 = Part.LineSegment(P007, P008)
	P009 = App.Vector(-0.0277, 19.9953, 0)
	P010 = App.Vector(0.0000, 19.6635, 0)
	S006 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(0.0000, 0.0000, 0)
	S007 = Part.LineSegment(P010, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_scarabase_facePlate_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.3500, App.Vector(40.0000, 91.0500, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scarabase_facePlate_Fa0():
	FC000 = ctr_face_scarabase_facePlate_Fa0_Ctr0()
	FC001 = ctr_face_scarabase_facePlate_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def scarabase_facePlate():
	FA000 = face_scarabase_facePlate_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scarabase_faceBack_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 20.0000, 0)
	P001 = App.Vector(80.0000, 20.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(80.0000, 131.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 131.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 20.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_scarabase_faceBack_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.5000, App.Vector(30.0000, 60.7500, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scarabase_faceBack_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.5000, App.Vector(50.0000, 60.7500, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scarabase_faceBack_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.5000, App.Vector(30.0000, 90.7500, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scarabase_faceBack_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(2.5000, App.Vector(50.0000, 90.7500, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scarabase_faceBack_Fa0():
	FC000 = ctr_face_scarabase_faceBack_Fa0_Ctr0()
	FC001 = ctr_face_scarabase_faceBack_Fa0_Ctr1()
	FC002 = ctr_face_scarabase_faceBack_Fa0_Ctr2()
	FC003 = ctr_face_scarabase_faceBack_Fa0_Ctr3()
	FC004 = ctr_face_scarabase_faceBack_Fa0_Ctr4()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004])
	rOneFace.check()
	return rOneFace

def scarabase_faceBack():
	FA000 = face_scarabase_faceBack_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scarabase_faceT3_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(3.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(3.0000, 20.1683, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(2.9723, 20.5001, 0)
	P004 = App.Vector(2.8899, 20.8228, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(-14.8532, 72.0517, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(40.0000, 149.1000, 0)
	P007 = App.Vector(94.8532, 72.0517, 0)
	S004 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(77.1101, 20.8228, 0)
	S005 = Part.LineSegment(P007, P008)
	P009 = App.Vector(77.0277, 20.5001, 0)
	P010 = App.Vector(77.0000, 20.1683, 0)
	S006 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(77.0000, 0.0000, 0)
	S007 = Part.LineSegment(P010, P011)
	P012 = App.Vector(80.0000, 0.0000, 0)
	S008 = Part.LineSegment(P011, P012)
	P013 = App.Vector(80.0000, 19.6635, 0)
	S009 = Part.LineSegment(P012, P013)
	P014 = App.Vector(80.0277, 19.9953, 0)
	P015 = App.Vector(80.1101, 20.3180, 0)
	S010 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(97.6879, 71.0699, 0)
	S011 = Part.LineSegment(P015, P016)
	P017 = App.Vector(40.0000, 152.1000, 0)
	P018 = App.Vector(-17.6879, 71.0699, 0)
	S012 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-0.1101, 20.3180, 0)
	S013 = Part.LineSegment(P018, P019)
	P020 = App.Vector(-0.0277, 19.9953, 0)
	P021 = App.Vector(0.0000, 19.6635, 0)
	S014 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(0.0000, 0.0000, 0)
	S015 = Part.LineSegment(P021, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scarabase_faceT3_Fa0():
	FC000 = ctr_face_scarabase_faceT3_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_scarabase_faceT3_Fa1_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(13.3500, App.Vector(40.0000, 91.0500, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scarabase_faceT3_Fa1_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.3500, App.Vector(40.0000, 91.0500, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scarabase_faceT3_Fa1():
	FC000 = ctr_face_scarabase_faceT3_Fa1_Ctr0()
	FC001 = ctr_face_scarabase_faceT3_Fa1_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def scarabase_faceT3():
	FA000 = face_scarabase_faceT3_Fa0()
	FA001 = face_scarabase_faceT3_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_scarabase_faceSide_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 10.0000, 0)
	P001 = App.Vector(77.7000, 10.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(77.7000, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(80.7000, 0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(80.7000, 20.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(10.0000, 20.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(10.0000, 131.5000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(80.7000, 131.5000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(80.7000, 151.5000, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(77.7000, 151.5000, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(77.7000, 141.5000, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(0.0000, 141.5000, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(0.0000, 10.0000, 0)
	S011 = Part.LineSegment(P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scarabase_faceSide_Fa0():
	FC000 = ctr_face_scarabase_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_scarabase_faceSide_Fa1_Ctr0():
	P000 = App.Vector(101.4000, 0.0000, 0)
	P001 = App.Vector(104.4000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(104.4000, 10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(149.1000, 10.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(149.1000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(152.1000, 0.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(152.1000, 20.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(101.4000, 20.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(101.4000, 0.0000, 0)
	S007 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scarabase_faceSide_Fa1():
	FC000 = ctr_face_scarabase_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_scarabase_faceSide_Fa2_Ctr0():
	P000 = App.Vector(101.4000, 131.5000, 0)
	P001 = App.Vector(152.1000, 131.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(152.1000, 151.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(149.1000, 151.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(149.1000, 141.5000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(104.4000, 141.5000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(104.4000, 151.5000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(101.4000, 151.5000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(101.4000, 131.5000, 0)
	S007 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scarabase_faceSide_Fa2():
	FC000 = ctr_face_scarabase_faceSide_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def scarabase_faceSide():
	FA000 = face_scarabase_faceSide_Fa0()
	FA001 = face_scarabase_faceSide_Fa1()
	FA002 = face_scarabase_faceSide_Fa2()
	rOneFig = FA000.fuse([FA001, FA002])
	rOneFig.check()
	return rOneFig

def fex_subpax_scarabase_plate2():
	FIG = scarabase_facePlate()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 10.0000))
	return VFP
subpax_scarabase_plate2 = fex_subpax_scarabase_plate2()

def fex_subpax_scarabase_plate4():
	FIG = scarabase_facePlate()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 131.5000))
	return VFP
subpax_scarabase_plate4 = fex_subpax_scarabase_plate4()

def fex_subpax_scarabase_back():
	FIG = scarabase_faceBack()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 10.0000, 0.0000))
	return VFP
subpax_scarabase_back = fex_subpax_scarabase_back()

def fex_subpax_scarabase_t31():
	FIG = scarabase_faceT3()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_scarabase_t31 = fex_subpax_scarabase_t31()

def fex_subpax_scarabase_t35():
	FIG = scarabase_faceT3()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 141.5000))
	return VFP
subpax_scarabase_t35 = fex_subpax_scarabase_t35()

def fvol_pax_scarabase():
	V000 = subpax_scarabase_plate2
	V001 = V000.fuse(subpax_scarabase_plate4)
	V002 = V001.fuse(subpax_scarabase_back)
	V003 = V002.fuse(subpax_scarabase_t31)
	V004 = V003.fuse(subpax_scarabase_t35)
	VFC = V004.removeSplitter()
	return VFC
pax_scarabase = fvol_pax_scarabase()

def ctr_face_scara1_facePlate_Fa0_Ctr0():
	P000 = App.Vector(65.7168, 60.8714, 0)
	P001 = App.Vector(-0.0000, 0.0000, 0)
	P002 = App.Vector(65.7168, -60.8714, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(199.9256, -50.5517, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(246.7500, 0.0000, 0)
	P005 = App.Vector(199.9256, 50.5517, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(65.7168, 60.8714, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_scara1_facePlate_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.2000, App.Vector(61.0500, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara1_facePlate_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.3500, App.Vector(196.0500, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scara1_facePlate_Fa0():
	FC000 = ctr_face_scara1_facePlate_Fa0_Ctr0()
	FC001 = ctr_face_scara1_facePlate_Fa0_Ctr1()
	FC002 = ctr_face_scara1_facePlate_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def scara1_facePlate():
	FA000 = face_scara1_facePlate_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scara1_faceIntern_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(13.2000, App.Vector(61.0500, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara1_faceIntern_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.2000, App.Vector(61.0500, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scara1_faceIntern_Fa0():
	FC000 = ctr_face_scara1_faceIntern_Fa0_Ctr0()
	FC001 = ctr_face_scara1_faceIntern_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_scara1_faceIntern_Fa1_Ctr0():
	P000 = App.Vector(20.2843, 41.3275, 0)
	P001 = App.Vector(61.0500, 58.0500, 0)
	P002 = App.Vector(101.8157, 41.3275, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(102.0979, 41.2123, 0)
	P004 = App.Vector(102.3794, 41.3294, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(103.9351, 42.8851, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(104.0522, 43.1693, 0)
	P007 = App.Vector(103.9332, 43.4526, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(97.0081, 49.3368, 0)
	P009 = App.Vector(89.2862, 54.1278, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(88.7874, 55.2897, 0)
	P011 = App.Vector(89.8257, 56.0114, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(143.9192, 51.8369, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(144.2217, 51.9422, 0)
	P014 = App.Vector(144.3500, 52.2357, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(144.3500, 54.4421, 0)
	S008 = Part.LineSegment(P014, P015)
	P016 = App.Vector(144.2435, 54.7138, 0)
	P017 = App.Vector(143.9807, 54.8409, 0)
	S009 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(65.7168, 60.8714, 0)
	S010 = Part.LineSegment(P017, P018)
	P019 = App.Vector(40.0506, 57.3247, 0)
	P020 = App.Vector(18.1668, 43.4526, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(18.0478, 43.1693, 0)
	P022 = App.Vector(18.1649, 42.8851, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(19.7206, 41.3294, 0)
	S013 = Part.LineSegment(P022, P023)
	P024 = App.Vector(20.0021, 41.2123, 0)
	P025 = App.Vector(20.2843, 41.3275, 0)
	S014 = Part.Arc(P023, P024, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara1_faceIntern_Fa1():
	FC000 = ctr_face_scara1_faceIntern_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_scara1_faceIntern_Fa2_Ctr0():
	P000 = App.Vector(20.2843, -41.3275, 0)
	P001 = App.Vector(61.0500, -58.0500, 0)
	P002 = App.Vector(101.8157, -41.3275, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(102.0979, -41.2123, 0)
	P004 = App.Vector(102.3794, -41.3294, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(103.9351, -42.8851, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(104.0522, -43.1693, 0)
	P007 = App.Vector(103.9332, -43.4526, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(97.0081, -49.3368, 0)
	P009 = App.Vector(89.2862, -54.1278, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(88.7874, -55.2897, 0)
	P011 = App.Vector(89.8257, -56.0114, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(143.9192, -51.8369, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(144.2217, -51.9422, 0)
	P014 = App.Vector(144.3500, -52.2357, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(144.3500, -54.4421, 0)
	S008 = Part.LineSegment(P014, P015)
	P016 = App.Vector(144.2435, -54.7138, 0)
	P017 = App.Vector(143.9807, -54.8409, 0)
	S009 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(65.7168, -60.8714, 0)
	S010 = Part.LineSegment(P017, P018)
	P019 = App.Vector(40.0506, -57.3247, 0)
	P020 = App.Vector(18.1668, -43.4526, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(18.0478, -43.1693, 0)
	P022 = App.Vector(18.1649, -42.8851, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(19.7206, -41.3294, 0)
	S013 = Part.LineSegment(P022, P023)
	P024 = App.Vector(20.0021, -41.2123, 0)
	P025 = App.Vector(20.2843, -41.3275, 0)
	S014 = Part.Arc(P023, P024, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara1_faceIntern_Fa2():
	FC000 = ctr_face_scara1_faceIntern_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def scara1_faceIntern():
	FA000 = face_scara1_faceIntern_Fa0()
	FA001 = face_scara1_faceIntern_Fa1()
	FA002 = face_scara1_faceIntern_Fa2()
	rOneFig = FA000.fuse([FA001, FA002])
	rOneFig.check()
	return rOneFig

def ctr_face_scara1_faceExtern_Fa0_Ctr0():
	P000 = App.Vector(123.4693, 53.4347, 0)
	P001 = App.Vector(199.6963, 47.5604, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(208.9237, 45.9299, 0)
	P003 = App.Vector(217.6544, 42.5269, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(218.1601, 41.9200, 0)
	P005 = App.Vector(218.0675, 41.1354, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(201.8162, 12.9874, 0)
	S003 = Part.LineSegment(P005, P006)
	P007 = App.Vector(201.2925, 12.5478, 0)
	P008 = App.Vector(200.6087, 12.5475, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(189.3750, 11.5614, 0)
	P010 = App.Vector(182.9042, 2.3258, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(182.5620, 1.7338, 0)
	P012 = App.Vector(181.9194, 1.5000, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(123.5000, 1.5000, 0)
	S007 = Part.LineSegment(P012, P013)
	P014 = App.Vector(123.2172, 1.3828, 0)
	P015 = App.Vector(123.1000, 1.1000, 0)
	S008 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(123.1000, -1.1000, 0)
	S009 = Part.LineSegment(P015, P016)
	P017 = App.Vector(123.2172, -1.3828, 0)
	P018 = App.Vector(123.5000, -1.5000, 0)
	S010 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(181.9194, -1.5000, 0)
	S011 = Part.LineSegment(P018, P019)
	P020 = App.Vector(182.5620, -1.7338, 0)
	P021 = App.Vector(182.9042, -2.3258, 0)
	S012 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(189.3750, -11.5614, 0)
	P023 = App.Vector(200.6087, -12.5475, 0)
	S013 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(201.2925, -12.5478, 0)
	P025 = App.Vector(201.8162, -12.9874, 0)
	S014 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(218.0675, -41.1354, 0)
	S015 = Part.LineSegment(P025, P026)
	P027 = App.Vector(218.1601, -41.9200, 0)
	P028 = App.Vector(217.6544, -42.5269, 0)
	S016 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(208.9237, -45.9299, 0)
	P030 = App.Vector(199.6963, -47.5604, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(123.4693, -53.4347, 0)
	S018 = Part.LineSegment(P030, P031)
	P032 = App.Vector(123.2065, -53.5618, 0)
	P033 = App.Vector(123.1000, -53.8335, 0)
	S019 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(123.1000, -56.0400, 0)
	S020 = Part.LineSegment(P033, P034)
	P035 = App.Vector(123.2282, -56.3335, 0)
	P036 = App.Vector(123.5307, -56.4388, 0)
	S021 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(199.9256, -50.5517, 0)
	S022 = Part.LineSegment(P036, P037)
	P038 = App.Vector(246.7500, 0.0000, 0)
	P039 = App.Vector(199.9256, 50.5517, 0)
	S023 = Part.Arc(P037, P038, P039)
	P040 = App.Vector(123.5307, 56.4388, 0)
	S024 = Part.LineSegment(P039, P040)
	P041 = App.Vector(123.2282, 56.3335, 0)
	P042 = App.Vector(123.1000, 56.0400, 0)
	S025 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(123.1000, 53.8335, 0)
	S026 = Part.LineSegment(P042, P043)
	P044 = App.Vector(123.2065, 53.5618, 0)
	P045 = App.Vector(123.4693, 53.4347, 0)
	S027 = Part.Arc(P043, P044, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_scara1_faceExtern_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.3500, App.Vector(196.0500, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara1_faceExtern_Fa0_Ctr2():
	P000 = App.Vector(204.6371, 10.2217, 0)
	P001 = App.Vector(209.4000, -0.0000, 0)
	P002 = App.Vector(204.6371, -10.2217, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(204.2955, -10.8141, 0)
	P004 = App.Vector(204.4143, -11.4874, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(220.6656, -39.6354, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(221.2987, -40.1079, 0)
	P007 = App.Vector(222.0772, -39.9734, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(243.7500, 0.0000, 0)
	P009 = App.Vector(222.0772, 39.9734, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(221.2987, 40.1079, 0)
	P011 = App.Vector(220.6656, 39.6354, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(204.4143, 11.4874, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(204.2955, 10.8141, 0)
	P014 = App.Vector(204.6371, 10.2217, 0)
	S007 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara1_faceExtern_Fa0():
	FC000 = ctr_face_scara1_faceExtern_Fa0_Ctr0()
	FC001 = ctr_face_scara1_faceExtern_Fa0_Ctr1()
	FC002 = ctr_face_scara1_faceExtern_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def scara1_faceExtern():
	FA000 = face_scara1_faceExtern_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scara1_faceH41_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(61.0500, App.Vector(61.0500, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara1_faceH41_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.2000, App.Vector(61.0500, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scara1_faceH41_Fa0():
	FC000 = ctr_face_scara1_faceH41_Fa0_Ctr0()
	FC001 = ctr_face_scara1_faceH41_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def scara1_faceH41():
	FA000 = face_scara1_faceH41_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scara1_faceH42_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(50.7000, App.Vector(196.0500, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara1_faceH42_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.3500, App.Vector(196.0500, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scara1_faceH42_Fa0():
	FC000 = ctr_face_scara1_faceH42_Fa0_Ctr0()
	FC001 = ctr_face_scara1_faceH42_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def scara1_faceH42():
	FA000 = face_scara1_faceH42_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scara1_faceSide_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 10.0000, 0)
	P001 = App.Vector(246.7500, 10.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(246.7500, 20.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 20.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 10.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara1_faceSide_Fa0():
	FC000 = ctr_face_scara1_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_scara1_faceSide_Fa1_Ctr0():
	P000 = App.Vector(0.0000, 111.0000, 0)
	P001 = App.Vector(246.7500, 111.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(246.7500, 121.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 121.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 111.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara1_faceSide_Fa1():
	FC000 = ctr_face_scara1_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def scara1_faceSide():
	FA000 = face_scara1_faceSide_Fa0()
	FA001 = face_scara1_faceSide_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def fex_subpax_scara1_plate2():
	FIG = scara1_facePlate()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 10.0000))
	return VFP
subpax_scara1_plate2 = fex_subpax_scara1_plate2()

def fex_subpax_scara1_int3():
	FIG = scara1_faceIntern()
	VEX = FIG.extrude(App.Vector(0, 0, 91))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 20.0000))
	return VFP
subpax_scara1_int3 = fex_subpax_scara1_int3()

def fex_subpax_scara1_plate4():
	FIG = scara1_facePlate()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 111.0000))
	return VFP
subpax_scara1_plate4 = fex_subpax_scara1_plate4()

def fex_subpax_scara1_ext1():
	FIG = scara1_faceExtern()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_scara1_ext1 = fex_subpax_scara1_ext1()

def fex_subpax_scara1_ext5():
	FIG = scara1_faceExtern()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 121.0000))
	return VFP
subpax_scara1_ext5 = fex_subpax_scara1_ext5()

def fvol_pax_scara1():
	V000 = subpax_scara1_plate2
	V001 = V000.fuse(subpax_scara1_int3)
	V002 = V001.fuse(subpax_scara1_plate4)
	V003 = V002.fuse(subpax_scara1_ext1)
	V004 = V003.fuse(subpax_scara1_ext5)
	VFC = V004.removeSplitter()
	return VFC
pax_scara1 = fvol_pax_scara1()

def ctr_face_scara2_facePlate_Fa0_Ctr0():
	P000 = App.Vector(55.1487, 50.5044, 0)
	P001 = App.Vector(-0.0000, 0.0000, 0)
	P002 = App.Vector(55.1487, -50.5044, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(171.7405, -40.1944, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(208.5500, 0.0000, 0)
	P005 = App.Vector(171.7405, 40.1944, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(55.1487, 50.5044, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_scara2_facePlate_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.2000, App.Vector(50.7000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara2_facePlate_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.3500, App.Vector(168.2000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scara2_facePlate_Fa0():
	FC000 = ctr_face_scara2_facePlate_Fa0_Ctr0()
	FC001 = ctr_face_scara2_facePlate_Fa0_Ctr1()
	FC002 = ctr_face_scara2_facePlate_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def scara2_facePlate():
	FA000 = face_scara2_facePlate_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scara2_faceIntern_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(13.2000, App.Vector(50.7000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara2_faceIntern_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.2000, App.Vector(50.7000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scara2_faceIntern_Fa0():
	FC000 = ctr_face_scara2_faceIntern_Fa0_Ctr0()
	FC001 = ctr_face_scara2_faceIntern_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_scara2_faceIntern_Fa1_Ctr0():
	P000 = App.Vector(17.2527, 34.0083, 0)
	P001 = App.Vector(50.7000, 47.7000, 0)
	P002 = App.Vector(84.1473, 34.0083, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(84.4295, 33.8935, 0)
	P004 = App.Vector(84.7107, 34.0107, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(86.2663, 35.5663, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(86.3835, 35.8508, 0)
	P007 = App.Vector(86.2641, 36.1343, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(81.5621, 40.2246, 0)
	P009 = App.Vector(76.3937, 43.7072, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(75.9482, 44.8744, 0)
	P011 = App.Vector(76.9890, 45.5654, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(126.4146, 41.1756, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(126.7200, 41.2790, 0)
	P014 = App.Vector(126.8500, 41.5740, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(126.8500, 43.7824, 0)
	S008 = Part.LineSegment(P014, P015)
	P016 = App.Vector(126.7451, 44.0525, 0)
	P017 = App.Vector(126.4853, 44.1809, 0)
	S009 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(55.1487, 50.5044, 0)
	S010 = Part.LineSegment(P017, P018)
	P019 = App.Vector(33.5633, 47.7161, 0)
	P020 = App.Vector(15.1359, 36.1343, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(15.0165, 35.8508, 0)
	P022 = App.Vector(15.1337, 35.5663, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(16.6893, 34.0107, 0)
	S013 = Part.LineSegment(P022, P023)
	P024 = App.Vector(16.9705, 33.8935, 0)
	P025 = App.Vector(17.2527, 34.0083, 0)
	S014 = Part.Arc(P023, P024, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara2_faceIntern_Fa1():
	FC000 = ctr_face_scara2_faceIntern_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_scara2_faceIntern_Fa2_Ctr0():
	P000 = App.Vector(17.2527, -34.0083, 0)
	P001 = App.Vector(50.7000, -47.7000, 0)
	P002 = App.Vector(84.1473, -34.0083, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(84.4295, -33.8935, 0)
	P004 = App.Vector(84.7107, -34.0107, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(86.2663, -35.5663, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(86.3835, -35.8508, 0)
	P007 = App.Vector(86.2641, -36.1343, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(81.5621, -40.2246, 0)
	P009 = App.Vector(76.3937, -43.7072, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(75.9482, -44.8744, 0)
	P011 = App.Vector(76.9890, -45.5654, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(126.4146, -41.1756, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(126.7200, -41.2790, 0)
	P014 = App.Vector(126.8500, -41.5740, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(126.8500, -43.7824, 0)
	S008 = Part.LineSegment(P014, P015)
	P016 = App.Vector(126.7451, -44.0525, 0)
	P017 = App.Vector(126.4853, -44.1809, 0)
	S009 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(55.1487, -50.5044, 0)
	S010 = Part.LineSegment(P017, P018)
	P019 = App.Vector(33.5633, -47.7161, 0)
	P020 = App.Vector(15.1359, -36.1343, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(15.0165, -35.8508, 0)
	P022 = App.Vector(15.1337, -35.5663, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(16.6893, -34.0107, 0)
	S013 = Part.LineSegment(P022, P023)
	P024 = App.Vector(16.9705, -33.8935, 0)
	P025 = App.Vector(17.2527, -34.0083, 0)
	S014 = Part.Arc(P023, P024, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara2_faceIntern_Fa2():
	FC000 = ctr_face_scara2_faceIntern_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def scara2_faceIntern():
	FA000 = face_scara2_faceIntern_Fa0()
	FA001 = face_scara2_faceIntern_Fa1()
	FA002 = face_scara2_faceIntern_Fa2()
	rOneFig = FA000.fuse([FA001, FA002])
	rOneFig.check()
	return rOneFig

def ctr_face_scara2_faceExtern_Fa0_Ctr0():
	P000 = App.Vector(102.7647, 43.2984, 0)
	P001 = App.Vector(171.4773, 37.2059, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(178.2097, 35.9837, 0)
	P003 = App.Vector(184.6062, 33.5538, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(185.1233, 32.9474, 0)
	P005 = App.Vector(185.0329, 32.1555, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(173.9662, 12.9874, 0)
	S003 = Part.LineSegment(P005, P006)
	P007 = App.Vector(173.4425, 12.5478, 0)
	P008 = App.Vector(172.7587, 12.5475, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(161.5250, 11.5614, 0)
	P010 = App.Vector(155.0542, 2.3258, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(154.7120, 1.7338, 0)
	P012 = App.Vector(154.0694, 1.5000, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(102.8000, 1.5000, 0)
	S007 = Part.LineSegment(P012, P013)
	P014 = App.Vector(102.5172, 1.3828, 0)
	P015 = App.Vector(102.4000, 1.1000, 0)
	S008 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(102.4000, -1.1000, 0)
	S009 = Part.LineSegment(P015, P016)
	P017 = App.Vector(102.5172, -1.3828, 0)
	P018 = App.Vector(102.8000, -1.5000, 0)
	S010 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(154.0694, -1.5000, 0)
	S011 = Part.LineSegment(P018, P019)
	P020 = App.Vector(154.7120, -1.7338, 0)
	P021 = App.Vector(155.0542, -2.3258, 0)
	S012 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(161.5250, -11.5614, 0)
	P023 = App.Vector(172.7587, -12.5475, 0)
	S013 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(173.4425, -12.5478, 0)
	P025 = App.Vector(173.9662, -12.9874, 0)
	S014 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(185.0329, -32.1555, 0)
	S015 = Part.LineSegment(P025, P026)
	P027 = App.Vector(185.1233, -32.9474, 0)
	P028 = App.Vector(184.6062, -33.5538, 0)
	S016 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(178.2097, -35.9837, 0)
	P030 = App.Vector(171.4773, -37.2059, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(102.7647, -43.2984, 0)
	S018 = Part.LineSegment(P030, P031)
	P032 = App.Vector(102.5049, -43.4267, 0)
	P033 = App.Vector(102.4000, -43.6968, 0)
	S019 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(102.4000, -45.9053, 0)
	S020 = Part.LineSegment(P033, P034)
	P035 = App.Vector(102.5299, -46.2003, 0)
	P036 = App.Vector(102.8353, -46.3037, 0)
	S021 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(171.7405, -40.1944, 0)
	S022 = Part.LineSegment(P036, P037)
	P038 = App.Vector(208.5500, 0.0000, 0)
	P039 = App.Vector(171.7405, 40.1944, 0)
	S023 = Part.Arc(P037, P038, P039)
	P040 = App.Vector(102.8353, 46.3037, 0)
	S024 = Part.LineSegment(P039, P040)
	P041 = App.Vector(102.5299, 46.2003, 0)
	P042 = App.Vector(102.4000, 45.9053, 0)
	S025 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(102.4000, 43.6968, 0)
	S026 = Part.LineSegment(P042, P043)
	P044 = App.Vector(102.5049, 43.4267, 0)
	P045 = App.Vector(102.7647, 43.2984, 0)
	S027 = Part.Arc(P043, P044, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_scara2_faceExtern_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.3500, App.Vector(168.2000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara2_faceExtern_Fa0_Ctr2():
	P000 = App.Vector(176.7871, 10.2217, 0)
	P001 = App.Vector(181.5500, -0.0000, 0)
	P002 = App.Vector(176.7871, -10.2217, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(176.4455, -10.8141, 0)
	P004 = App.Vector(176.5643, -11.4874, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(187.6310, -30.6555, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(188.2716, -31.1297, 0)
	P007 = App.Vector(189.0554, -30.9851, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(205.5500, 0.0000, 0)
	P009 = App.Vector(189.0554, 30.9851, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(188.2716, 31.1297, 0)
	P011 = App.Vector(187.6310, 30.6555, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(176.5643, 11.4874, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(176.4455, 10.8141, 0)
	P014 = App.Vector(176.7871, 10.2217, 0)
	S007 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara2_faceExtern_Fa0():
	FC000 = ctr_face_scara2_faceExtern_Fa0_Ctr0()
	FC001 = ctr_face_scara2_faceExtern_Fa0_Ctr1()
	FC002 = ctr_face_scara2_faceExtern_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def scara2_faceExtern():
	FA000 = face_scara2_faceExtern_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scara2_faceH41_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(50.7000, App.Vector(50.7000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara2_faceH41_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.2000, App.Vector(50.7000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scara2_faceH41_Fa0():
	FC000 = ctr_face_scara2_faceH41_Fa0_Ctr0()
	FC001 = ctr_face_scara2_faceH41_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def scara2_faceH41():
	FA000 = face_scara2_faceH41_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scara2_faceH42_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(40.3500, App.Vector(168.2000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara2_faceH42_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.3500, App.Vector(168.2000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scara2_faceH42_Fa0():
	FC000 = ctr_face_scara2_faceH42_Fa0_Ctr0()
	FC001 = ctr_face_scara2_faceH42_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def scara2_faceH42():
	FA000 = face_scara2_faceH42_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scara2_faceSide_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 10.0000, 0)
	P001 = App.Vector(208.5500, 10.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(208.5500, 20.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 20.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 10.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara2_faceSide_Fa0():
	FC000 = ctr_face_scara2_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_scara2_faceSide_Fa1_Ctr0():
	P000 = App.Vector(0.0000, 90.5000, 0)
	P001 = App.Vector(208.5500, 90.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(208.5500, 100.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 100.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 90.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara2_faceSide_Fa1():
	FC000 = ctr_face_scara2_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def scara2_faceSide():
	FA000 = face_scara2_faceSide_Fa0()
	FA001 = face_scara2_faceSide_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def fex_subpax_scara2_plate2():
	FIG = scara2_facePlate()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 10.0000))
	return VFP
subpax_scara2_plate2 = fex_subpax_scara2_plate2()

def fex_subpax_scara2_int3():
	FIG = scara2_faceIntern()
	VEX = FIG.extrude(App.Vector(0, 0, 70.5))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 20.0000))
	return VFP
subpax_scara2_int3 = fex_subpax_scara2_int3()

def fex_subpax_scara2_plate4():
	FIG = scara2_facePlate()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 90.5000))
	return VFP
subpax_scara2_plate4 = fex_subpax_scara2_plate4()

def fex_subpax_scara2_ext1():
	FIG = scara2_faceExtern()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_scara2_ext1 = fex_subpax_scara2_ext1()

def fex_subpax_scara2_ext5():
	FIG = scara2_faceExtern()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 100.5000))
	return VFP
subpax_scara2_ext5 = fex_subpax_scara2_ext5()

def fvol_pax_scara2():
	V000 = subpax_scara2_plate2
	V001 = V000.fuse(subpax_scara2_int3)
	V002 = V001.fuse(subpax_scara2_plate4)
	V003 = V002.fuse(subpax_scara2_ext1)
	V004 = V003.fuse(subpax_scara2_ext5)
	VFC = V004.removeSplitter()
	return VFC
pax_scara2 = fvol_pax_scara2()

def ctr_face_scara3_facePlate_Fa0_Ctr0():
	P000 = App.Vector(44.5040, 40.1356, 0)
	P001 = App.Vector(0.0000, 0.0000, 0)
	P002 = App.Vector(44.5040, -40.1356, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(143.4385, -29.8406, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(170.3500, 0.0000, 0)
	P005 = App.Vector(143.4385, 29.8406, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(44.5040, 40.1356, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_scara3_facePlate_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.2000, App.Vector(40.3500, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara3_facePlate_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.3500, App.Vector(140.3500, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scara3_facePlate_Fa0():
	FC000 = ctr_face_scara3_facePlate_Fa0_Ctr0()
	FC001 = ctr_face_scara3_facePlate_Fa0_Ctr1()
	FC002 = ctr_face_scara3_facePlate_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def scara3_facePlate():
	FA000 = face_scara3_facePlate_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scara3_faceIntern_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(13.2000, App.Vector(40.3500, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara3_faceIntern_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.2000, App.Vector(40.3500, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scara3_faceIntern_Fa0():
	FC000 = ctr_face_scara3_faceIntern_Fa0_Ctr0()
	FC001 = ctr_face_scara3_faceIntern_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_scara3_faceIntern_Fa1_Ctr0():
	P000 = App.Vector(14.2209, 26.6888, 0)
	P001 = App.Vector(40.3500, 37.3500, 0)
	P002 = App.Vector(66.4791, 26.6888, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(66.7611, 26.5746, 0)
	P004 = App.Vector(67.0418, 26.6918, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(68.5975, 28.2475, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(68.7147, 28.5323, 0)
	P007 = App.Vector(68.5947, 28.8160, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(65.9662, 31.1758, 0)
	P009 = App.Vector(63.1415, 33.2967, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(62.7677, 34.4669, 0)
	P011 = App.Vector(63.8104, 35.1165, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(108.9084, 30.3989, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(109.2177, 30.4996, 0)
	P014 = App.Vector(109.3500, 30.7968, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(109.3500, 33.0083, 0)
	S008 = Part.LineSegment(P014, P015)
	P016 = App.Vector(109.2472, 33.2761, 0)
	P017 = App.Vector(108.9915, 33.4062, 0)
	S009 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(44.5040, 40.1356, 0)
	S010 = Part.LineSegment(P017, P018)
	P019 = App.Vector(27.0413, 38.0920, 0)
	P020 = App.Vector(12.1053, 28.8160, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(11.9853, 28.5323, 0)
	P022 = App.Vector(12.1025, 28.2475, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(13.6582, 26.6918, 0)
	S013 = Part.LineSegment(P022, P023)
	P024 = App.Vector(13.9389, 26.5746, 0)
	P025 = App.Vector(14.2209, 26.6888, 0)
	S014 = Part.Arc(P023, P024, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara3_faceIntern_Fa1():
	FC000 = ctr_face_scara3_faceIntern_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_scara3_faceIntern_Fa2_Ctr0():
	P000 = App.Vector(14.2209, -26.6888, 0)
	P001 = App.Vector(40.3500, -37.3500, 0)
	P002 = App.Vector(66.4791, -26.6888, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(66.7611, -26.5746, 0)
	P004 = App.Vector(67.0418, -26.6918, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(68.5975, -28.2475, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(68.7147, -28.5323, 0)
	P007 = App.Vector(68.5947, -28.8160, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(65.9662, -31.1758, 0)
	P009 = App.Vector(63.1415, -33.2967, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(62.7677, -34.4669, 0)
	P011 = App.Vector(63.8104, -35.1165, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(108.9084, -30.3989, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(109.2177, -30.4996, 0)
	P014 = App.Vector(109.3500, -30.7968, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(109.3500, -33.0083, 0)
	S008 = Part.LineSegment(P014, P015)
	P016 = App.Vector(109.2472, -33.2761, 0)
	P017 = App.Vector(108.9915, -33.4062, 0)
	S009 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(44.5040, -40.1356, 0)
	S010 = Part.LineSegment(P017, P018)
	P019 = App.Vector(27.0413, -38.0920, 0)
	P020 = App.Vector(12.1053, -28.8160, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(11.9853, -28.5323, 0)
	P022 = App.Vector(12.1025, -28.2475, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(13.6582, -26.6918, 0)
	S013 = Part.LineSegment(P022, P023)
	P024 = App.Vector(13.9389, -26.5746, 0)
	P025 = App.Vector(14.2209, -26.6888, 0)
	S014 = Part.Arc(P023, P024, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara3_faceIntern_Fa2():
	FC000 = ctr_face_scara3_faceIntern_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def scara3_faceIntern():
	FA000 = face_scara3_faceIntern_Fa0()
	FA001 = face_scara3_faceIntern_Fa1()
	FA002 = face_scara3_faceIntern_Fa2()
	rOneFig = FA000.fuse([FA001, FA002])
	rOneFig.check()
	return rOneFig

def ctr_face_scara3_faceExtern_Fa0_Ctr0():
	P000 = App.Vector(82.0585, 33.2324, 0)
	P001 = App.Vector(143.1297, 26.8565, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(147.4271, 26.0560, 0)
	P003 = App.Vector(151.5391, 24.5724, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(152.0770, 23.9673, 0)
	P005 = App.Vector(151.9907, 23.1623, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(146.1162, 12.9874, 0)
	S003 = Part.LineSegment(P005, P006)
	P007 = App.Vector(145.5925, 12.5478, 0)
	P008 = App.Vector(144.9087, 12.5475, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(133.6750, 11.5614, 0)
	P010 = App.Vector(127.2042, 2.3258, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(126.8620, 1.7338, 0)
	P012 = App.Vector(126.2194, 1.5000, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(82.1000, 1.5000, 0)
	S007 = Part.LineSegment(P012, P013)
	P014 = App.Vector(81.8172, 1.3828, 0)
	P015 = App.Vector(81.7000, 1.1000, 0)
	S008 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(81.7000, -1.1000, 0)
	S009 = Part.LineSegment(P015, P016)
	P017 = App.Vector(81.8172, -1.3828, 0)
	P018 = App.Vector(82.1000, -1.5000, 0)
	S010 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(126.2194, -1.5000, 0)
	S011 = Part.LineSegment(P018, P019)
	P020 = App.Vector(126.8620, -1.7338, 0)
	P021 = App.Vector(127.2042, -2.3258, 0)
	S012 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(133.6750, -11.5614, 0)
	P023 = App.Vector(144.9087, -12.5475, 0)
	S013 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(145.5925, -12.5478, 0)
	P025 = App.Vector(146.1162, -12.9874, 0)
	S014 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(151.9907, -23.1623, 0)
	S015 = Part.LineSegment(P025, P026)
	P027 = App.Vector(152.0770, -23.9673, 0)
	P028 = App.Vector(151.5391, -24.5724, 0)
	S016 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(147.4271, -26.0560, 0)
	P030 = App.Vector(143.1297, -26.8565, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(82.0585, -33.2324, 0)
	S018 = Part.LineSegment(P030, P031)
	P032 = App.Vector(81.8028, -33.3625, 0)
	P033 = App.Vector(81.7000, -33.6302, 0)
	S019 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(81.7000, -35.8419, 0)
	S020 = Part.LineSegment(P033, P034)
	P035 = App.Vector(81.8322, -36.1391, 0)
	P036 = App.Vector(82.1415, -36.2397, 0)
	S021 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(143.4385, -29.8406, 0)
	S022 = Part.LineSegment(P036, P037)
	P038 = App.Vector(170.3500, 0.0000, 0)
	P039 = App.Vector(143.4385, 29.8406, 0)
	S023 = Part.Arc(P037, P038, P039)
	P040 = App.Vector(82.1415, 36.2397, 0)
	S024 = Part.LineSegment(P039, P040)
	P041 = App.Vector(81.8322, 36.1391, 0)
	P042 = App.Vector(81.7000, 35.8419, 0)
	S025 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(81.7000, 33.6302, 0)
	S026 = Part.LineSegment(P042, P043)
	P044 = App.Vector(81.8028, 33.3625, 0)
	P045 = App.Vector(82.0585, 33.2324, 0)
	S027 = Part.Arc(P043, P044, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_scara3_faceExtern_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.3500, App.Vector(140.3500, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara3_faceExtern_Fa0_Ctr2():
	P000 = App.Vector(148.9371, 10.2217, 0)
	P001 = App.Vector(153.7000, 0.0000, 0)
	P002 = App.Vector(148.9371, -10.2217, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(148.5955, -10.8141, 0)
	P004 = App.Vector(148.7143, -11.4874, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(154.5888, -21.6623, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(155.2428, -22.1396, 0)
	P007 = App.Vector(156.0358, -21.9763, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(167.3500, 0.0000, 0)
	P009 = App.Vector(156.0358, 21.9763, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(155.2428, 22.1396, 0)
	P011 = App.Vector(154.5888, 21.6623, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(148.7143, 11.4874, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(148.5955, 10.8141, 0)
	P014 = App.Vector(148.9371, 10.2217, 0)
	S007 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara3_faceExtern_Fa0():
	FC000 = ctr_face_scara3_faceExtern_Fa0_Ctr0()
	FC001 = ctr_face_scara3_faceExtern_Fa0_Ctr1()
	FC002 = ctr_face_scara3_faceExtern_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def scara3_faceExtern():
	FA000 = face_scara3_faceExtern_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scara3_faceH41_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(40.3500, App.Vector(40.3500, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara3_faceH41_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.2000, App.Vector(40.3500, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scara3_faceH41_Fa0():
	FC000 = ctr_face_scara3_faceH41_Fa0_Ctr0()
	FC001 = ctr_face_scara3_faceH41_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def scara3_faceH41():
	FA000 = face_scara3_faceH41_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scara3_faceH42_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(30.0000, App.Vector(140.3500, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara3_faceH42_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.3500, App.Vector(140.3500, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scara3_faceH42_Fa0():
	FC000 = ctr_face_scara3_faceH42_Fa0_Ctr0()
	FC001 = ctr_face_scara3_faceH42_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def scara3_faceH42():
	FA000 = face_scara3_faceH42_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scara3_faceSide_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 10.0000, 0)
	P001 = App.Vector(170.3500, 10.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(170.3500, 20.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 20.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 10.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara3_faceSide_Fa0():
	FC000 = ctr_face_scara3_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_scara3_faceSide_Fa1_Ctr0():
	P000 = App.Vector(0.0000, 70.0000, 0)
	P001 = App.Vector(170.3500, 70.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(170.3500, 80.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 80.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 70.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara3_faceSide_Fa1():
	FC000 = ctr_face_scara3_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def scara3_faceSide():
	FA000 = face_scara3_faceSide_Fa0()
	FA001 = face_scara3_faceSide_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def fex_subpax_scara3_plate2():
	FIG = scara3_facePlate()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 10.0000))
	return VFP
subpax_scara3_plate2 = fex_subpax_scara3_plate2()

def fex_subpax_scara3_int3():
	FIG = scara3_faceIntern()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 20.0000))
	return VFP
subpax_scara3_int3 = fex_subpax_scara3_int3()

def fex_subpax_scara3_plate4():
	FIG = scara3_facePlate()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 70.0000))
	return VFP
subpax_scara3_plate4 = fex_subpax_scara3_plate4()

def fex_subpax_scara3_ext1():
	FIG = scara3_faceExtern()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_scara3_ext1 = fex_subpax_scara3_ext1()

def fex_subpax_scara3_ext5():
	FIG = scara3_faceExtern()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 80.0000))
	return VFP
subpax_scara3_ext5 = fex_subpax_scara3_ext5()

def fvol_pax_scara3():
	V000 = subpax_scara3_plate2
	V001 = V000.fuse(subpax_scara3_int3)
	V002 = V001.fuse(subpax_scara3_plate4)
	V003 = V002.fuse(subpax_scara3_ext1)
	V004 = V003.fuse(subpax_scara3_ext5)
	VFC = V004.removeSplitter()
	return VFC
pax_scara3 = fvol_pax_scara3()

def finh_inpax_long2d_base():
	IVR1 = pax_scarabase.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	IVF = IVR3.translate(App.Vector(0.0000, 40.0000, 0.0000))
	return IVF
inpax_long2d_base = finh_inpax_long2d_base()

def finh_inpax_long2d_leg_1():
	IVR1 = pax_scara1.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	IVF = IVR3.translate(App.Vector(219.7800, 40.0000, 0.0000))
	return IVF
inpax_long2d_leg_1 = finh_inpax_long2d_leg_1()

def finh_inpax_long2d_leg_2():
	IVR1 = pax_scara2.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	IVF = IVR3.translate(App.Vector(366.3000, 40.0000, 0.0000))
	return IVF
inpax_long2d_leg_2 = finh_inpax_long2d_leg_2()

def finh_inpax_long2d_leg_3():
	IVR1 = pax_scara3.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	IVF = IVR3.translate(App.Vector(512.8200, 40.0000, 0.0000))
	return IVF
inpax_long2d_leg_3 = finh_inpax_long2d_leg_3()

def fex_subpax_long2d_axis_1():
	FIG = long2d_faceAxis()
	VEX = FIG.extrude(App.Vector(0, 0, 151.5))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(30.0000, 20.0000, 0.0000))
	return VFP
subpax_long2d_axis_1 = fex_subpax_long2d_axis_1()

def fex_subpax_long2d_axis_2():
	FIG = long2d_faceAxis()
	VEX = FIG.extrude(App.Vector(0, 0, 131))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(60.0000, 20.0000, 0.0000))
	return VFP
subpax_long2d_axis_2 = fex_subpax_long2d_axis_2()

def fex_subpax_long2d_axis_3():
	FIG = long2d_faceAxis()
	VEX = FIG.extrude(App.Vector(0, 0, 110.5))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(90.0000, 20.0000, 0.0000))
	return VFP
subpax_long2d_axis_3 = fex_subpax_long2d_axis_3()

def fvol_pax_long2d():
	V000 = inpax_long2d_base
	V001 = V000.fuse(inpax_long2d_leg_1)
	V002 = V001.fuse(inpax_long2d_leg_2)
	V003 = V002.fuse(inpax_long2d_leg_3)
	V004 = V003.fuse(subpax_long2d_axis_1)
	V005 = V004.fuse(subpax_long2d_axis_2)
	V006 = V005.fuse(subpax_long2d_axis_3)
	VFC = V006.removeSplitter()
	return VFC
pax_long2d = fvol_pax_long2d()


pax_long2d.check()
#pax_long2d.exportBrep(f"{outFileName}.brep")
#pax_long2d.exportIges(f"{outFileName}.igs")
#pax_long2d.exportStep(f"{outFileName}.stp")
pax_long2d.exportStl(f"{outFileName}.stl")

