# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "scara"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_scara_facePlate_Fa0_Ctr0():
	P000 = App.Vector(31.4981, 29.9626, 0)
	P001 = App.Vector(-0.0000, 0.0000, 0)
	P002 = App.Vector(31.4981, -29.9626, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(230.9988, -19.9750, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(250.0000, 0.0000, 0)
	P005 = App.Vector(230.9988, 19.9750, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(31.4981, 29.9626, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_scara_facePlate_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(30.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara_facePlate_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(230.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scara_facePlate_Fa0():
	FC000 = ctr_face_scara_facePlate_Fa0_Ctr0()
	FC001 = ctr_face_scara_facePlate_Fa0_Ctr1()
	FC002 = ctr_face_scara_facePlate_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def scara_facePlate():
	FA000 = face_scara_facePlate_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scara_faceIntern_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(12.0000, App.Vector(30.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara_faceIntern_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(30.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scara_faceIntern_Fa0():
	FC000 = ctr_face_scara_faceIntern_Fa0_Ctr0()
	FC001 = ctr_face_scara_faceIntern_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_scara_faceIntern_Fa1_Ctr0():
	P000 = App.Vector(10.5514, 20.1433, 0)
	P001 = App.Vector(30.0000, 28.0000, 0)
	P002 = App.Vector(49.4486, 20.1433, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(49.8003, 20.0030, 0)
	P004 = App.Vector(50.1494, 20.1494, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(50.8567, 20.8567, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(51.0031, 21.2144, 0)
	P007 = App.Vector(50.8506, 21.5697, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(48.5361, 23.5884, 0)
	P009 = App.Vector(46.0272, 25.3600, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(45.6082, 26.5073, 0)
	P011 = App.Vector(46.6115, 27.2041, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(199.4750, 19.5488, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(199.8446, 19.6859, 0)
	P014 = App.Vector(200.0000, 20.0482, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(200.0000, 21.0494, 0)
	S008 = Part.LineSegment(P014, P015)
	P016 = App.Vector(199.8623, 21.3940, 0)
	P017 = App.Vector(199.5250, 21.5488, 0)
	S009 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(31.4981, 29.9626, 0)
	S010 = Part.LineSegment(P017, P018)
	P019 = App.Vector(19.4530, 28.0849, 0)
	P020 = App.Vector(9.1494, 21.5697, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(8.9969, 21.2144, 0)
	P022 = App.Vector(9.1433, 20.8567, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(9.8506, 20.1494, 0)
	S013 = Part.LineSegment(P022, P023)
	P024 = App.Vector(10.1997, 20.0030, 0)
	P025 = App.Vector(10.5514, 20.1433, 0)
	S014 = Part.Arc(P023, P024, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara_faceIntern_Fa1():
	FC000 = ctr_face_scara_faceIntern_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_scara_faceIntern_Fa2_Ctr0():
	P000 = App.Vector(10.5514, -20.1433, 0)
	P001 = App.Vector(30.0000, -28.0000, 0)
	P002 = App.Vector(49.4486, -20.1433, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(49.8003, -20.0030, 0)
	P004 = App.Vector(50.1494, -20.1494, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(50.8567, -20.8567, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(51.0031, -21.2144, 0)
	P007 = App.Vector(50.8506, -21.5697, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(48.5361, -23.5884, 0)
	P009 = App.Vector(46.0272, -25.3600, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(45.6082, -26.5073, 0)
	P011 = App.Vector(46.6115, -27.2041, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(199.4750, -19.5488, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(199.8446, -19.6859, 0)
	P014 = App.Vector(200.0000, -20.0482, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(200.0000, -21.0494, 0)
	S008 = Part.LineSegment(P014, P015)
	P016 = App.Vector(199.8623, -21.3940, 0)
	P017 = App.Vector(199.5250, -21.5488, 0)
	S009 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(31.4981, -29.9626, 0)
	S010 = Part.LineSegment(P017, P018)
	P019 = App.Vector(19.4530, -28.0849, 0)
	P020 = App.Vector(9.1494, -21.5697, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(8.9969, -21.2144, 0)
	P022 = App.Vector(9.1433, -20.8567, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(9.8506, -20.1494, 0)
	S013 = Part.LineSegment(P022, P023)
	P024 = App.Vector(10.1997, -20.0030, 0)
	P025 = App.Vector(10.5514, -20.1433, 0)
	S014 = Part.Arc(P023, P024, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara_faceIntern_Fa2():
	FC000 = ctr_face_scara_faceIntern_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def scara_faceIntern():
	FA000 = face_scara_faceIntern_Fa0()
	FA001 = face_scara_faceIntern_Fa1()
	FA002 = face_scara_faceIntern_Fa2()
	rOneFig = FA000.fuse([FA001, FA002])
	rOneFig.check()
	return rOneFig

def ctr_face_scara_faceExtern_Fa0_Ctr0():
	P000 = App.Vector(70.4750, 26.0112, 0)
	P001 = App.Vector(230.8989, 17.9775, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(234.0654, 17.5349, 0)
	P003 = App.Vector(237.1036, 16.5390, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(237.6579, 15.9355, 0)
	P005 = App.Vector(237.5749, 15.1202, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(233.0070, 7.2082, 0)
	S003 = Part.LineSegment(P005, P006)
	P007 = App.Vector(232.5194, 6.7826, 0)
	P008 = App.Vector(231.8733, 6.7447, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(226.5000, 6.0622, 0)
	P010 = App.Vector(223.2223, 1.7500, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(222.8664, 1.2094, 0)
	P012 = App.Vector(222.2540, 1.0000, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(70.5000, 1.0000, 0)
	S007 = Part.LineSegment(P012, P013)
	P014 = App.Vector(70.1464, 0.8536, 0)
	P015 = App.Vector(70.0000, 0.5000, 0)
	S008 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(70.0000, -0.5000, 0)
	S009 = Part.LineSegment(P015, P016)
	P017 = App.Vector(70.1464, -0.8536, 0)
	P018 = App.Vector(70.5000, -1.0000, 0)
	S010 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(222.2540, -1.0000, 0)
	S011 = Part.LineSegment(P018, P019)
	P020 = App.Vector(222.8664, -1.2094, 0)
	P021 = App.Vector(223.2223, -1.7500, 0)
	S012 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(226.5000, -6.0622, 0)
	P023 = App.Vector(231.8733, -6.7447, 0)
	S013 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(232.5194, -6.7826, 0)
	P025 = App.Vector(233.0070, -7.2082, 0)
	S014 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(237.5749, -15.1202, 0)
	S015 = Part.LineSegment(P025, P026)
	P027 = App.Vector(237.6579, -15.9355, 0)
	P028 = App.Vector(237.1036, -16.5390, 0)
	S016 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(234.0654, -17.5349, 0)
	P030 = App.Vector(230.8989, -17.9775, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(70.4750, -26.0112, 0)
	S018 = Part.LineSegment(P030, P031)
	P032 = App.Vector(70.1377, -26.1660, 0)
	P033 = App.Vector(70.0000, -26.5106, 0)
	S019 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(70.0000, -27.5118, 0)
	S020 = Part.LineSegment(P033, P034)
	P035 = App.Vector(70.1554, -27.8741, 0)
	P036 = App.Vector(70.5250, -28.0112, 0)
	S021 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(230.9988, -19.9750, 0)
	S022 = Part.LineSegment(P036, P037)
	P038 = App.Vector(250.0000, 0.0000, 0)
	P039 = App.Vector(230.9988, 19.9750, 0)
	S023 = Part.Arc(P037, P038, P039)
	P040 = App.Vector(70.5250, 28.0112, 0)
	S024 = Part.LineSegment(P039, P040)
	P041 = App.Vector(70.1554, 27.8741, 0)
	P042 = App.Vector(70.0000, 27.5118, 0)
	S025 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(70.0000, 26.5106, 0)
	S026 = Part.LineSegment(P042, P043)
	P044 = App.Vector(70.1377, 26.1660, 0)
	P045 = App.Vector(70.4750, 26.0112, 0)
	S027 = Part.Arc(P043, P044, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_scara_faceExtern_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(230.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara_faceExtern_Fa0_Ctr2():
	P000 = App.Vector(234.9044, 4.9947, 0)
	P001 = App.Vector(237.0000, 0.0000, 0)
	P002 = App.Vector(234.9044, -4.9947, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(234.6142, -5.5732, 0)
	P004 = App.Vector(234.7390, -6.2082, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(239.3070, -14.1202, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(239.9716, -14.5997, 0)
	P007 = App.Vector(240.7714, -14.4214, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(248.0000, -0.0000, 0)
	P009 = App.Vector(240.7714, 14.4214, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(239.9716, 14.5997, 0)
	P011 = App.Vector(239.3070, 14.1202, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(234.7390, 6.2082, 0)
	S006 = Part.LineSegment(P011, P012)
	P013 = App.Vector(234.6142, 5.5732, 0)
	P014 = App.Vector(234.9044, 4.9947, 0)
	S007 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara_faceExtern_Fa0():
	FC000 = ctr_face_scara_faceExtern_Fa0_Ctr0()
	FC001 = ctr_face_scara_faceExtern_Fa0_Ctr1()
	FC002 = ctr_face_scara_faceExtern_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def scara_faceExtern():
	FA000 = face_scara_faceExtern_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scara_faceH41_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(30.0000, App.Vector(30.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara_faceH41_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(30.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scara_faceH41_Fa0():
	FC000 = ctr_face_scara_faceH41_Fa0_Ctr0()
	FC001 = ctr_face_scara_faceH41_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def scara_faceH41():
	FA000 = face_scara_faceH41_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scara_faceH42_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(230.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_scara_faceH42_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(230.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_scara_faceH42_Fa0():
	FC000 = ctr_face_scara_faceH42_Fa0_Ctr0()
	FC001 = ctr_face_scara_faceH42_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def scara_faceH42():
	FA000 = face_scara_faceH42_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_scara_faceSide_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 5.0000, 0)
	P001 = App.Vector(250.0000, 5.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(250.0000, 7.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 7.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 5.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara_faceSide_Fa0():
	FC000 = ctr_face_scara_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_scara_faceSide_Fa1_Ctr0():
	P000 = App.Vector(0.0000, 57.0000, 0)
	P001 = App.Vector(250.0000, 57.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(250.0000, 59.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 59.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 57.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_scara_faceSide_Fa1():
	FC000 = ctr_face_scara_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def scara_faceSide():
	FA000 = face_scara_faceSide_Fa0()
	FA001 = face_scara_faceSide_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def fex_subpax_scara_plate2():
	FIG = scara_facePlate()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 5.0000))
	return VFP
subpax_scara_plate2 = fex_subpax_scara_plate2()

def fex_subpax_scara_int3():
	FIG = scara_faceIntern()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 7.0000))
	return VFP
subpax_scara_int3 = fex_subpax_scara_int3()

def fex_subpax_scara_plate4():
	FIG = scara_facePlate()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 57.0000))
	return VFP
subpax_scara_plate4 = fex_subpax_scara_plate4()

def fex_subpax_scara_ext1():
	FIG = scara_faceExtern()
	VEX = FIG.extrude(App.Vector(0, 0, 5))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_scara_ext1 = fex_subpax_scara_ext1()

def fex_subpax_scara_ext5():
	FIG = scara_faceExtern()
	VEX = FIG.extrude(App.Vector(0, 0, 5))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 59.0000))
	return VFP
subpax_scara_ext5 = fex_subpax_scara_ext5()

def fvol_pax_scara():
	V000 = subpax_scara_plate2
	V001 = V000.fuse(subpax_scara_int3)
	V002 = V001.fuse(subpax_scara_plate4)
	V003 = V002.fuse(subpax_scara_ext1)
	V004 = V003.fuse(subpax_scara_ext5)
	VFC = V004.removeSplitter()
	return VFC
pax_scara = fvol_pax_scara()


pax_scara.check()
#pax_scara.exportBrep(f"{outFileName}.brep")
#pax_scara.exportIges(f"{outFileName}.igs")
#pax_scara.exportStep(f"{outFileName}.stp")
pax_scara.exportStl(f"{outFileName}.stl")

