# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "pivot"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_pivot_faceTopPlate1_Fa0_Ctr0():
	P000 = App.Vector(104.0000, 40.0000, 0)
	P001 = App.Vector(69.8179, 40.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(69.3003, 39.9319, 0)
	P003 = App.Vector(68.8179, 39.7321, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(45.0000, 25.9808, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(43.5196, 25.7714, 0)
	P006 = App.Vector(42.3077, 26.6469, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-50.0000, 0.0000, 0)
	P008 = App.Vector(42.3077, -26.6469, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(43.5196, -25.7714, 0)
	P010 = App.Vector(45.0000, -25.9808, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(68.8179, -39.7321, 0)
	S006 = Part.LineSegment(P010, P011)
	P012 = App.Vector(69.3003, -39.9319, 0)
	P013 = App.Vector(69.8179, -40.0000, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(104.0000, -40.0000, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(104.0000, 40.0000, 0)
	S009 = Part.LineSegment(P014, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pivot_faceTopPlate1_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(30.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pivot_faceTopPlate1_Fa0_Ctr2():
	P000 = App.Vector(93.0000, 38.0000, 0)
	P001 = App.Vector(70.3538, 38.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(69.8362, 37.9319, 0)
	P003 = App.Vector(69.3538, 37.7321, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(60.5000, 32.6203, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(58.6699, 30.7902, 0)
	P006 = App.Vector(58.0000, 28.2902, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(58.0000, -28.2902, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(58.6699, -30.7902, 0)
	P009 = App.Vector(60.5000, -32.6203, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(69.3538, -37.7321, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(69.8362, -37.9319, 0)
	P012 = App.Vector(70.3538, -38.0000, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(93.0000, -38.0000, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(96.5355, -36.5355, 0)
	P015 = App.Vector(98.0000, -33.0000, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(98.0000, 33.0000, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(96.5355, 36.5355, 0)
	P018 = App.Vector(93.0000, 38.0000, 0)
	S011 = Part.Arc(P016, P017, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pivot_faceTopPlate1_Fa0():
	FC000 = ctr_face_pivot_faceTopPlate1_Fa0_Ctr0()
	FC001 = ctr_face_pivot_faceTopPlate1_Fa0_Ctr1()
	FC002 = ctr_face_pivot_faceTopPlate1_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def pivot_faceTopPlate1():
	FA000 = face_pivot_faceTopPlate1_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pivot_faceTopPlate2_Fa0_Ctr0():
	P000 = App.Vector(104.0000, 40.0000, 0)
	P001 = App.Vector(69.8179, 40.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(69.3003, 39.9319, 0)
	P003 = App.Vector(68.8179, 39.7321, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(45.0000, 25.9808, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(43.5196, 25.7714, 0)
	P006 = App.Vector(42.3077, 26.6469, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-50.0000, 0.0000, 0)
	P008 = App.Vector(42.3077, -26.6469, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(43.5196, -25.7714, 0)
	P010 = App.Vector(45.0000, -25.9808, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(68.8179, -39.7321, 0)
	S006 = Part.LineSegment(P010, P011)
	P012 = App.Vector(69.3003, -39.9319, 0)
	P013 = App.Vector(69.8179, -40.0000, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(104.0000, -40.0000, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(104.0000, -38.0000, 0)
	S009 = Part.LineSegment(P014, P015)
	P016 = App.Vector(100.0000, -38.0000, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(100.0000, 38.0000, 0)
	S011 = Part.LineSegment(P016, P017)
	P018 = App.Vector(104.0000, 38.0000, 0)
	S012 = Part.LineSegment(P017, P018)
	P019 = App.Vector(104.0000, 40.0000, 0)
	S013 = Part.LineSegment(P018, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pivot_faceTopPlate2_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(30.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pivot_faceTopPlate2_Fa0_Ctr2():
	P000 = App.Vector(93.0000, 38.0000, 0)
	P001 = App.Vector(70.3538, 38.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(69.8362, 37.9319, 0)
	P003 = App.Vector(69.3538, 37.7321, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(60.5000, 32.6203, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(58.6699, 30.7902, 0)
	P006 = App.Vector(58.0000, 28.2902, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(58.0000, -28.2902, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(58.6699, -30.7902, 0)
	P009 = App.Vector(60.5000, -32.6203, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(69.3538, -37.7321, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(69.8362, -37.9319, 0)
	P012 = App.Vector(70.3538, -38.0000, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(93.0000, -38.0000, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(96.5355, -36.5355, 0)
	P015 = App.Vector(98.0000, -33.0000, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(98.0000, 33.0000, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(96.5355, 36.5355, 0)
	P018 = App.Vector(93.0000, 38.0000, 0)
	S011 = Part.Arc(P016, P017, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pivot_faceTopPlate2_Fa0():
	FC000 = ctr_face_pivot_faceTopPlate2_Fa0_Ctr0()
	FC001 = ctr_face_pivot_faceTopPlate2_Fa0_Ctr1()
	FC002 = ctr_face_pivot_faceTopPlate2_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def pivot_faceTopPlate2():
	FA000 = face_pivot_faceTopPlate2_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pivot_faceTopH5_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(50.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pivot_faceTopH5_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(30.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_pivot_faceTopH5_Fa0():
	FC000 = ctr_face_pivot_faceTopH5_Fa0_Ctr0()
	FC001 = ctr_face_pivot_faceTopH5_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def pivot_faceTopH5():
	FA000 = face_pivot_faceTopH5_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pivot_faceTopWall1_Fa0_Ctr0():
	P000 = App.Vector(104.0000, 40.0000, 0)
	P001 = App.Vector(69.8179, 40.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(69.3003, 39.9319, 0)
	P003 = App.Vector(68.8179, 39.7321, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(45.0000, 25.9808, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(43.5196, 25.7714, 0)
	P006 = App.Vector(42.3077, 26.6469, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-50.0000, 0.0000, 0)
	P008 = App.Vector(42.3077, -26.6469, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(43.5196, -25.7714, 0)
	P010 = App.Vector(45.0000, -25.9808, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(68.8179, -39.7321, 0)
	S006 = Part.LineSegment(P010, P011)
	P012 = App.Vector(69.3003, -39.9319, 0)
	P013 = App.Vector(69.8179, -40.0000, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(104.0000, -40.0000, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(104.0000, -38.0000, 0)
	S009 = Part.LineSegment(P014, P015)
	P016 = App.Vector(70.3511, -38.0000, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(69.8359, -37.9325, 0)
	P018 = App.Vector(69.3555, -37.7346, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(44.2586, -23.3314, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(42.7444, -23.1344, 0)
	P021 = App.Vector(41.5326, -24.0634, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(-48.0000, -0.0000, 0)
	P023 = App.Vector(41.5326, 24.0634, 0)
	S014 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(42.7444, 23.1344, 0)
	P025 = App.Vector(44.2586, 23.3314, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(69.3555, 37.7346, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(69.8359, 37.9325, 0)
	P028 = App.Vector(70.3511, 38.0000, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(104.0000, 38.0000, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(104.0000, 40.0000, 0)
	S019 = Part.LineSegment(P029, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pivot_faceTopWall1_Fa0():
	FC000 = ctr_face_pivot_faceTopWall1_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_pivot_faceTopWall1_Fa1_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(35.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pivot_faceTopWall1_Fa1_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(30.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_pivot_faceTopWall1_Fa1():
	FC000 = ctr_face_pivot_faceTopWall1_Fa1_Ctr0()
	FC001 = ctr_face_pivot_faceTopWall1_Fa1_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def pivot_faceTopWall1():
	FA000 = face_pivot_faceTopWall1_Fa0()
	FA001 = face_pivot_faceTopWall1_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_pivot_faceTopWall2_Fa0_Ctr0():
	P000 = App.Vector(104.0000, 40.0000, 0)
	P001 = App.Vector(69.8179, 40.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(69.3003, 39.9319, 0)
	P003 = App.Vector(68.8179, 39.7321, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(45.0000, 25.9808, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(43.5196, 25.7714, 0)
	P006 = App.Vector(42.3077, 26.6469, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(7.7337, 49.3983, 0)
	P008 = App.Vector(-32.1394, 38.3022, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(-30.8538, 36.7701, 0)
	S005 = Part.LineSegment(P008, P009)
	P010 = App.Vector(8.2991, 47.2771, 0)
	P011 = App.Vector(41.5326, 24.0634, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(42.7444, 23.1344, 0)
	P013 = App.Vector(44.2586, 23.3314, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(69.3555, 37.7346, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(69.8359, 37.9325, 0)
	P016 = App.Vector(70.3511, 38.0000, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(104.0000, 38.0000, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(104.0000, 40.0000, 0)
	S011 = Part.LineSegment(P017, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pivot_faceTopWall2_Fa0():
	FC000 = ctr_face_pivot_faceTopWall2_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_pivot_faceTopWall2_Fa1_Ctr0():
	P000 = App.Vector(104.0000, -40.0000, 0)
	P001 = App.Vector(69.8179, -40.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(69.3003, -39.9319, 0)
	P003 = App.Vector(68.8179, -39.7321, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(45.0000, -25.9808, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(43.5196, -25.7714, 0)
	P006 = App.Vector(42.3077, -26.6469, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(7.7337, -49.3983, 0)
	P008 = App.Vector(-32.1394, -38.3022, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(-30.8538, -36.7701, 0)
	S005 = Part.LineSegment(P008, P009)
	P010 = App.Vector(8.2991, -47.2771, 0)
	P011 = App.Vector(41.5326, -24.0634, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(42.7444, -23.1344, 0)
	P013 = App.Vector(44.2586, -23.3314, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(69.3555, -37.7346, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(69.8359, -37.9325, 0)
	P016 = App.Vector(70.3511, -38.0000, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(104.0000, -38.0000, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(104.0000, -40.0000, 0)
	S011 = Part.LineSegment(P017, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pivot_faceTopWall2_Fa1():
	FC000 = ctr_face_pivot_faceTopWall2_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_pivot_faceTopWall2_Fa2_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(35.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_pivot_faceTopWall2_Fa2_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(30.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_pivot_faceTopWall2_Fa2():
	FC000 = ctr_face_pivot_faceTopWall2_Fa2_Ctr0()
	FC001 = ctr_face_pivot_faceTopWall2_Fa2_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def pivot_faceTopWall2():
	FA000 = face_pivot_faceTopWall2_Fa0()
	FA001 = face_pivot_faceTopWall2_Fa1()
	FA002 = face_pivot_faceTopWall2_Fa2()
	rOneFig = FA000.fuse([FA001, FA002])
	rOneFig.check()
	return rOneFig

def ctr_face_pivot_faceTopTube_Fa0_Ctr0():
	P000 = App.Vector(104.0000, 40.0000, 0)
	P001 = App.Vector(69.8179, 40.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(69.3003, 39.9319, 0)
	P003 = App.Vector(68.8179, 39.7321, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(52.0000, 30.0222, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(52.0000, 29.0222, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(56.0000, 29.0222, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(56.0000, -29.0222, 0)
	S005 = Part.LineSegment(P006, P007)
	P008 = App.Vector(52.0000, -29.0222, 0)
	S006 = Part.LineSegment(P007, P008)
	P009 = App.Vector(52.0000, -30.0222, 0)
	S007 = Part.LineSegment(P008, P009)
	P010 = App.Vector(68.8179, -39.7321, 0)
	S008 = Part.LineSegment(P009, P010)
	P011 = App.Vector(69.3003, -39.9319, 0)
	P012 = App.Vector(69.8179, -40.0000, 0)
	S009 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(104.0000, -40.0000, 0)
	S010 = Part.LineSegment(P012, P013)
	P014 = App.Vector(104.0000, -38.0000, 0)
	S011 = Part.LineSegment(P013, P014)
	P015 = App.Vector(100.0000, -38.0000, 0)
	S012 = Part.LineSegment(P014, P015)
	P016 = App.Vector(100.0000, 38.0000, 0)
	S013 = Part.LineSegment(P015, P016)
	P017 = App.Vector(104.0000, 38.0000, 0)
	S014 = Part.LineSegment(P016, P017)
	P018 = App.Vector(104.0000, 40.0000, 0)
	S015 = Part.LineSegment(P017, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pivot_faceTopTube_Fa0_Ctr1():
	P000 = App.Vector(93.0000, 38.0000, 0)
	P001 = App.Vector(70.3538, 38.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(69.8362, 37.9319, 0)
	P003 = App.Vector(69.3538, 37.7321, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(60.5000, 32.6203, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(58.6699, 30.7902, 0)
	P006 = App.Vector(58.0000, 28.2902, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(58.0000, -28.2902, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(58.6699, -30.7902, 0)
	P009 = App.Vector(60.5000, -32.6203, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(69.3538, -37.7321, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(69.8362, -37.9319, 0)
	P012 = App.Vector(70.3538, -38.0000, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(93.0000, -38.0000, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(96.5355, -36.5355, 0)
	P015 = App.Vector(98.0000, -33.0000, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(98.0000, 33.0000, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(96.5355, 36.5355, 0)
	P018 = App.Vector(93.0000, 38.0000, 0)
	S011 = Part.Arc(P016, P017, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pivot_faceTopTube_Fa0():
	FC000 = ctr_face_pivot_faceTopTube_Fa0_Ctr0()
	FC001 = ctr_face_pivot_faceTopTube_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def pivot_faceTopTube():
	FA000 = face_pivot_faceTopTube_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pivot_faceTopPlate3_Fa0_Ctr0():
	P000 = App.Vector(-4.0000, -40.0000, 0)
	P001 = App.Vector(100.0000, -40.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(100.0000, 40.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-4.0000, 40.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-4.0000, -40.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pivot_faceTopPlate3_Fa0_Ctr1():
	P000 = App.Vector(93.0000, 38.0000, 0)
	P001 = App.Vector(70.3538, 38.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(69.8362, 37.9319, 0)
	P003 = App.Vector(69.3538, 37.7321, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(60.5000, 32.6203, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(58.6699, 30.7902, 0)
	P006 = App.Vector(58.0000, 28.2902, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(58.0000, -28.2902, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(58.6699, -30.7902, 0)
	P009 = App.Vector(60.5000, -32.6203, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(69.3538, -37.7321, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(69.8362, -37.9319, 0)
	P012 = App.Vector(70.3538, -38.0000, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(93.0000, -38.0000, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(96.5355, -36.5355, 0)
	P015 = App.Vector(98.0000, -33.0000, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(98.0000, 33.0000, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(96.5355, 36.5355, 0)
	P018 = App.Vector(93.0000, 38.0000, 0)
	S011 = Part.Arc(P016, P017, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pivot_faceTopPlate3_Fa0():
	FC000 = ctr_face_pivot_faceTopPlate3_Fa0_Ctr0()
	FC001 = ctr_face_pivot_faceTopPlate3_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def pivot_faceTopPlate3():
	FA000 = face_pivot_faceTopPlate3_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pivot_faceSidePlate_Fa0_Ctr0():
	P000 = App.Vector(-40.0000, 150.0000, 0)
	P001 = App.Vector(-40.0000, 90.3982, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-39.9842, 90.0013, 0)
	P003 = App.Vector(-39.9370, 89.6068, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-29.6219, 25.2521, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(0.0000, 0.0000, 0)
	P006 = App.Vector(29.6219, 25.2521, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(39.9370, 89.6068, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(39.9842, 90.0013, 0)
	P009 = App.Vector(40.0000, 90.3982, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(40.0000, 150.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-40.0000, 150.0000, 0)
	S007 = Part.LineSegment(P010, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pivot_faceSidePlate_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(0.0000, 30.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_pivot_faceSidePlate_Fa0():
	FC000 = ctr_face_pivot_faceSidePlate_Fa0_Ctr0()
	FC001 = ctr_face_pivot_faceSidePlate_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def pivot_faceSidePlate():
	FA000 = face_pivot_faceSidePlate_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pivot_faceSideArc_Fa0_Ctr0():
	P000 = App.Vector(-2.0000, 90.0000, 0)
	P001 = App.Vector(6.8604, 116.5811, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(8.6802, 119.0562, 0)
	P003 = App.Vector(11.6038, 120.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(84.3962, 120.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(87.3198, 119.0562, 0)
	P006 = App.Vector(89.1396, 116.5811, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(98.0000, 90.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(98.0000, 150.0000, 0)
	S005 = Part.LineSegment(P007, P008)
	P009 = App.Vector(-2.0000, 150.0000, 0)
	S006 = Part.LineSegment(P008, P009)
	P010 = App.Vector(-2.0000, 90.0000, 0)
	S007 = Part.LineSegment(P009, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pivot_faceSideArc_Fa0():
	FC000 = ctr_face_pivot_faceSideArc_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def pivot_faceSideArc():
	FA000 = face_pivot_faceSideArc_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pivot_faceRelief3_Fa0_Ctr0():
	P000 = App.Vector(-30.0222, 151.5000, 0)
	P001 = App.Vector(30.0222, 151.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(30.0222, 194.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-30.0222, 194.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-30.0222, 151.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pivot_faceRelief3_Fa0_Ctr1():
	P000 = App.Vector(-17.1895, 155.0000, 0)
	P001 = App.Vector(17.1895, 155.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.0938, 156.3885, 0)
	P003 = App.Vector(18.3540, 158.6260, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(1.1645, 170.9361, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-0.0000, 171.3101, 0)
	P006 = App.Vector(-1.1645, 170.9361, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-18.3540, 158.6260, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-19.0938, 156.3885, 0)
	P009 = App.Vector(-17.1895, 155.0000, 0)
	S005 = Part.Arc(P007, P008, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pivot_faceRelief3_Fa0_Ctr2():
	P000 = App.Vector(-17.1895, 191.0000, 0)
	P001 = App.Vector(17.1895, 191.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.0938, 189.6115, 0)
	P003 = App.Vector(18.3540, 187.3740, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(1.1645, 175.0639, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-0.0000, 174.6899, 0)
	P006 = App.Vector(-1.1645, 175.0639, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-18.3540, 187.3740, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-19.0938, 189.6115, 0)
	P009 = App.Vector(-17.1895, 191.0000, 0)
	S005 = Part.Arc(P007, P008, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pivot_faceRelief3_Fa0_Ctr3():
	P000 = App.Vector(-24.8577, 156.4284, 0)
	P001 = App.Vector(-3.9881, 171.3740, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-3.1526, 173.0000, 0)
	P003 = App.Vector(-3.9881, 174.6260, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-24.8577, 189.5716, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-26.9363, 189.7244, 0)
	P006 = App.Vector(-28.0222, 187.9455, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-28.0222, 158.0545, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-26.9363, 156.2756, 0)
	P009 = App.Vector(-24.8577, 156.4284, 0)
	S005 = Part.Arc(P007, P008, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pivot_faceRelief3_Fa0_Ctr4():
	P000 = App.Vector(24.8577, 156.4284, 0)
	P001 = App.Vector(3.9881, 171.3740, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(3.1526, 173.0000, 0)
	P003 = App.Vector(3.9881, 174.6260, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(24.8577, 189.5716, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(26.9363, 189.7244, 0)
	P006 = App.Vector(28.0222, 187.9455, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(28.0222, 158.0545, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(26.9363, 156.2756, 0)
	P009 = App.Vector(24.8577, 156.4284, 0)
	S005 = Part.Arc(P007, P008, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pivot_faceRelief3_Fa0():
	FC000 = ctr_face_pivot_faceRelief3_Fa0_Ctr0()
	FC001 = ctr_face_pivot_faceRelief3_Fa0_Ctr1()
	FC002 = ctr_face_pivot_faceRelief3_Fa0_Ctr2()
	FC003 = ctr_face_pivot_faceRelief3_Fa0_Ctr3()
	FC004 = ctr_face_pivot_faceRelief3_Fa0_Ctr4()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004])
	rOneFace.check()
	return rOneFace

def pivot_faceRelief3():
	FA000 = face_pivot_faceRelief3_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pivot_faceRelief4_Fa0_Ctr0():
	P000 = App.Vector(-38.0000, 196.0000, 0)
	P001 = App.Vector(-38.0000, 153.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-40.0000, 153.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-40.0000, 90.3982, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-39.9842, 90.0013, 0)
	P005 = App.Vector(-39.9370, 89.6068, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-29.6219, 25.2521, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(0.0000, 0.0000, 0)
	P008 = App.Vector(29.6219, 25.2521, 0)
	S005 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(39.9370, 89.6068, 0)
	S006 = Part.LineSegment(P008, P009)
	P010 = App.Vector(39.9842, 90.0013, 0)
	P011 = App.Vector(40.0000, 90.3982, 0)
	S007 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(40.0000, 153.0000, 0)
	S008 = Part.LineSegment(P011, P012)
	P013 = App.Vector(38.0000, 153.0000, 0)
	S009 = Part.LineSegment(P012, P013)
	P014 = App.Vector(38.0000, 196.0000, 0)
	S010 = Part.LineSegment(P013, P014)
	P015 = App.Vector(-38.0000, 196.0000, 0)
	S011 = Part.LineSegment(P014, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pivot_faceRelief4_Fa0_Ctr1():
	P000 = App.Vector(-37.0000, 187.0000, 0)
	P001 = App.Vector(-37.0000, 90.6371, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-36.9842, 90.2402, 0)
	P003 = App.Vector(-36.9370, 89.8458, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-26.6597, 25.7269, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(0.0000, 3.0000, 0)
	P006 = App.Vector(26.6597, 25.7269, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(36.9370, 89.8458, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(36.9842, 90.2402, 0)
	P009 = App.Vector(37.0000, 90.6371, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(37.0000, 187.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(35.5355, 190.5355, 0)
	P012 = App.Vector(32.0000, 192.0000, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(6.0000, 192.0000, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(2.4645, 190.5355, 0)
	P015 = App.Vector(1.0000, 187.0000, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(1.0000, 45.9060, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(1.8876, 43.0620, 0)
	P018 = App.Vector(4.2353, 41.2277, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(0.0000, 18.0000, 0)
	P020 = App.Vector(-4.2353, 41.2277, 0)
	S012 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(-1.8876, 43.0620, 0)
	P022 = App.Vector(-1.0000, 45.9060, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-1.0000, 187.0000, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-2.4645, 190.5355, 0)
	P025 = App.Vector(-6.0000, 192.0000, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-32.0000, 192.0000, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-35.5355, 190.5355, 0)
	P028 = App.Vector(-37.0000, 187.0000, 0)
	S017 = Part.Arc(P026, P027, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pivot_faceRelief4_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(0.0000, 30.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_pivot_faceRelief4_Fa0():
	FC000 = ctr_face_pivot_faceRelief4_Fa0_Ctr0()
	FC001 = ctr_face_pivot_faceRelief4_Fa0_Ctr1()
	FC002 = ctr_face_pivot_faceRelief4_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def pivot_faceRelief4():
	FA000 = face_pivot_faceRelief4_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pivot_faceRelief5_Fa0_Ctr0():
	P000 = App.Vector(-40.0000, 153.0000, 0)
	P001 = App.Vector(-40.0000, 90.3982, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-39.9842, 90.0013, 0)
	P003 = App.Vector(-39.9370, 89.6068, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-29.6219, 25.2521, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(0.0000, 0.0000, 0)
	P006 = App.Vector(29.6219, 25.2521, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(39.9370, 89.6068, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(39.9842, 90.0013, 0)
	P009 = App.Vector(40.0000, 90.3982, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(40.0000, 153.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-40.0000, 153.0000, 0)
	S007 = Part.LineSegment(P010, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pivot_faceRelief5_Fa0_Ctr1():
	P000 = App.Vector(-37.0000, 144.0000, 0)
	P001 = App.Vector(-37.0000, 90.6371, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-36.9842, 90.2402, 0)
	P003 = App.Vector(-36.9370, 89.8458, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-26.6597, 25.7269, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(0.0000, 3.0000, 0)
	P006 = App.Vector(26.6597, 25.7269, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(36.9370, 89.8458, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(36.9842, 90.2402, 0)
	P009 = App.Vector(37.0000, 90.6371, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(37.0000, 144.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(35.5355, 147.5355, 0)
	P012 = App.Vector(32.0000, 149.0000, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(6.0000, 149.0000, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(2.4645, 147.5355, 0)
	P015 = App.Vector(1.0000, 144.0000, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(1.0000, 45.9060, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(1.8876, 43.0620, 0)
	P018 = App.Vector(4.2353, 41.2277, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(0.0000, 18.0000, 0)
	P020 = App.Vector(-4.2353, 41.2277, 0)
	S012 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(-1.8876, 43.0620, 0)
	P022 = App.Vector(-1.0000, 45.9060, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-1.0000, 144.0000, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-2.4645, 147.5355, 0)
	P025 = App.Vector(-6.0000, 149.0000, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-32.0000, 149.0000, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-35.5355, 147.5355, 0)
	P028 = App.Vector(-37.0000, 144.0000, 0)
	S017 = Part.Arc(P026, P027, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_pivot_faceRelief5_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(0.0000, 30.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_pivot_faceRelief5_Fa0():
	FC000 = ctr_face_pivot_faceRelief5_Fa0_Ctr0()
	FC001 = ctr_face_pivot_faceRelief5_Fa0_Ctr1()
	FC002 = ctr_face_pivot_faceRelief5_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def pivot_faceRelief5():
	FA000 = face_pivot_faceRelief5_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_pivot_plate1():
	FIG = pivot_faceTopPlate1()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 286.0000))
	return VFP
subpax_pivot_plate1 = fex_subpax_pivot_plate1()

def fex_subpax_pivot_wall11():
	FIG = pivot_faceTopWall1()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 276.0000))
	return VFP
subpax_pivot_wall11 = fex_subpax_pivot_wall11()

def fex_subpax_pivot_wall2():
	FIG = pivot_faceTopWall2()
	VEX = FIG.extrude(App.Vector(0, 0, 70))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 206.0000))
	return VFP
subpax_pivot_wall2 = fex_subpax_pivot_wall2()

def fex_subpax_pivot_wall12():
	FIG = pivot_faceTopWall1()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 196.0000))
	return VFP
subpax_pivot_wall12 = fex_subpax_pivot_wall12()

def fex_subpax_pivot_plate2():
	FIG = pivot_faceTopPlate2()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 193.0000))
	return VFP
subpax_pivot_plate2 = fex_subpax_pivot_plate2()

def fex_subpax_pivot_h51():
	FIG = pivot_faceTopH5()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 289.0000))
	return VFP
subpax_pivot_h51 = fex_subpax_pivot_h51()

def fex_subpax_pivot_h52():
	FIG = pivot_faceTopH5()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 192.0000))
	return VFP
subpax_pivot_h52 = fex_subpax_pivot_h52()

def fex_subpax_pivot_tube():
	FIG = pivot_faceTopTube()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 153.0000))
	return VFP
subpax_pivot_tube = fex_subpax_pivot_tube()

def fex_subpax_pivot_plate3():
	FIG = pivot_faceTopPlate3()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 150.0000))
	return VFP
subpax_pivot_plate3 = fex_subpax_pivot_plate3()

def fex_subpax_pivot_sideplate5():
	FIG = pivot_faceSidePlate()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(-2.0000, 0.0000, 0.0000))
	return VFP
subpax_pivot_sideplate5 = fex_subpax_pivot_sideplate5()

def fex_subpax_pivot_sideplate4():
	FIG = pivot_faceSidePlate()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(100.0000, 0.0000, 0.0000))
	return VFP
subpax_pivot_sideplate4 = fex_subpax_pivot_sideplate4()

def fex_subpax_pivot_sidearc1():
	FIG = pivot_faceSideArc()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, -38.0000, 0.0000))
	return VFP
subpax_pivot_sidearc1 = fex_subpax_pivot_sidearc1()

def fex_subpax_pivot_sidearc2():
	FIG = pivot_faceSideArc()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 40.0000, 0.0000))
	return VFP
subpax_pivot_sidearc2 = fex_subpax_pivot_sidearc2()

def fex_subpax_pivot_siderelief3():
	FIG = pivot_faceRelief3()
	VEX = FIG.extrude(App.Vector(0, 0, 4))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(56.0000, 0.0000, 0.0000))
	return VFP
subpax_pivot_siderelief3 = fex_subpax_pivot_siderelief3()

def fex_subpax_pivot_siderelief5():
	FIG = pivot_faceRelief5()
	VEX = FIG.extrude(App.Vector(0, 0, 4))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(-4.0000, 0.0000, 0.0000))
	return VFP
subpax_pivot_siderelief5 = fex_subpax_pivot_siderelief5()

def fex_subpax_pivot_siderelief4():
	FIG = pivot_faceRelief4()
	VEX = FIG.extrude(App.Vector(0, 0, 4))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(104.0000, 0.0000, 0.0000))
	return VFP
subpax_pivot_siderelief4 = fex_subpax_pivot_siderelief4()

def fvol_pax_pivot():
	V000 = subpax_pivot_plate1
	V001 = V000.fuse(subpax_pivot_wall11)
	V002 = V001.fuse(subpax_pivot_wall2)
	V003 = V002.fuse(subpax_pivot_wall12)
	V004 = V003.fuse(subpax_pivot_plate2)
	V005 = V004.fuse(subpax_pivot_h51)
	V006 = V005.fuse(subpax_pivot_h52)
	V007 = V006.fuse(subpax_pivot_tube)
	V008 = V007.fuse(subpax_pivot_plate3)
	V009 = V008.fuse(subpax_pivot_sideplate5)
	V010 = V009.fuse(subpax_pivot_sideplate4)
	V011 = V010.fuse(subpax_pivot_sidearc1)
	V012 = V011.fuse(subpax_pivot_sidearc2)
	V013 = V012.fuse(subpax_pivot_siderelief3)
	V014 = V013.fuse(subpax_pivot_siderelief5)
	V015 = V014.fuse(subpax_pivot_siderelief4)
	VFC = V015.removeSplitter()
	return VFC
pax_pivot = fvol_pax_pivot()


pax_pivot.check()
#pax_pivot.exportBrep(f"{outFileName}.brep")
#pax_pivot.exportIges(f"{outFileName}.igs")
#pax_pivot.exportStep(f"{outFileName}.stp")
pax_pivot.exportStl(f"{outFileName}.stl")

